<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\ContactsController;
use FortisAPILib\Exceptions;

class ContactsControllerTest extends BaseTestController
{
    /**
     * @var ContactsController ContactsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getContactsController();
    }

    public function testViewSingleContact()
    {
        // Parameters for the API call
        $contactId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleContact($contactId, $expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Contact","data":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_nu' .
                'mber":"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smi' .
                'th","cell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state"' .
                ':"Michigan","postal_code":"48375","country":"USA"},"company_name":"Fortis Payme' .
                'nt Systems, LLC","header_message":"This is a sample message for you","date_of_b' .
                'irth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_p' .
                'hone":"3339998822","office_phone_ext":"5","home_phone_country_code":"+1","offic' .
                'e_phone_country_code":"+1","cell_phone_country_code":"+1","header_message_type"' .
                ':0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3"' .
                ':"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com",' .
                '"token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'reated_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","received_emails":[{"subject":"Payment Receipt - 12s' .
                'kiestech","body":"This email is being sent from a server.","source_address":"' .
                '\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestec' .
                'h A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-' .
                '8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","rea' .
                'son_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11' .
                'e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"is_deletable":true,"location' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204' .
                '0992,"account_number":"5454545454545454","address":{"city":"Novi","state":"MI",' .
                '"postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e0' .
                '93242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domai' .
                'n.com","fax":"3339998822","location_api_id":"location-111111","location_api_key' .
                '":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2",' .
                '"location_c3":"custom data 3","name":"Sample Company Headquarters","office_phon' .
                'e":"2481234567","office_ext_phone":"1021021209","tz":"America/New_York","parent' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":' .
                'true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","t' .
                'icket_hash_key":"A5F443CADF4AE34BBCAADF4"},"user":{"account_number":"5454545454' .
                '545454","branding_domain_url":"{branding_domain_url}","cell_phone":"3339998822"' .
                ',"company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","ema' .
                'il":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998822","firs' .
                't_name":"John","last_name":"Smith","locale":"en-US","office_phone":"3339998822"' .
                ',"office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requi' .
                'res_new_password":null,"terms_condition_code":"20220308","tz":"America/New_York' .
                '","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv"' .
                ',"process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f' .
                '1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_' .
                'key":null,"user_type_code":100,"password":null,"zip":"48375","location_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"' .
                'address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":14' .
                '22040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.16' .
                '8.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login":14220409' .
                '92,"log_api_response_body_ts":1422040992},"recurrings":[{"account_vault_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","account_vault_api_id":"token1234abcd","token_api_id":"t' .
                'oken1234abcd","_joi":{"conditions":{}},"active":true,"description":"Description' .
                '","end_date":"2021-12-01","installment_total_count":20,"interval":1,"interval_t' .
                'ype":"d","location_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"paymen' .
                't_method":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_dat' .
                'e":"2021-12-01","status":"active","transaction_amount":300,"terms_agree":true,"' .
                'terms_agree_ip":"192.168.0.10","recurring_c1":"recurring custom data 1","recurr' .
                'ing_c2":"recurring custom data 2","recurring_c3":"recurring custom data 3","sen' .
                'd_to_proc_as_recur":true,"tags":["Walk-in Customer"],"secondary_amount":100,"cu' .
                'rrency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","cre' .
                'ated_ts":1422040992,"modified_ts":1422040992,"recurring_type_id":"i","installme' .
                'nt_amount_total":99999999,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email' .
                '_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true' .
                ',"created_ts":1422040992},"sms_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isB' .
                'lacklisted":true,"detail":true,"created_ts":1422040992},"changelogs":[{"id":"11' .
                'e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"Tran' .
                'sactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"' .
                'user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_nam' .
                'e":"Bob","last_name":"Fairview"}}],"postback_logs":[{"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","postback_config_id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","next_run_ts":1422040992,"created_ts":1422040992,"model_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a"}],"created_user":{"account_number":"5454545454545454",' .
                '"branding_domain_url":"{branding_domain_url}","cell_phone":"3339998822","compan' .
                'y_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"ema' .
                'il@domain.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":' .
                '"John","last_name":"Smith","locale":"en-US","office_phone":"3339998822","office' .
                '_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_' .
                'password":null,"terms_condition_code":"20220308","tz":"America/New_York","ui_pr' .
                'efs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv","proces' .
                's_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"us' .
                'ername":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":nul' .
                'l,"user_type_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"address"' .
                ':{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f' .
                '8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992' .
                ',"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10",' .
                '"current_date_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_' .
                'api_response_body_ts":1422040992},"parent":{"location_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","account_number":"54545433332","contact_api_id":"137","first_name":"John"' .
                ',"last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"cit' .
                'y":"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"company_na' .
                'me":"Fortis Payment Systems, LLC","header_message":"This is a sample message fo' .
                'r you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339' .
                '998822","office_phone":"3339998822","office_phone_ext":"5","home_phone_country_' .
                'code":"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","hea' .
                'der_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anyth' .
                'ing","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"e' .
                'mail@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39' .
                'de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"' .
                'created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"children":{"location_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","first' .
                '_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.36,"a' .
                'ddress":{"city":"Novi","state":"Michigan","postal_code":"48375","country":"USA"' .
                '},"company_name":"Fortis Payment Systems, LLC","header_message":"This is a samp' .
                'le message for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home' .
                '_phone":"3339998822","office_phone":"3339998822","office_phone_ext":"5","home_p' .
                'hone_country_code":"+1","office_phone_country_code":"+1","cell_phone_country_co' .
                'de":"+1","header_message_type":0,"update_if_exists":1,"contact_c1":"any","conta' .
                'ct_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"a' .
                'ctive":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testContactsSearch()
    {
        // Parameters for the API call
        $locationId = '11e95f8ec39de8fbdb0a4f1a';
        $page = null;
        $keyword = null;
        $active = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->contactsSearch($locationId, $page, $keyword, $active);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"ContactSearchsCollection","list":[{"location_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","account_number":"54545433332","contact_api_id":"137","first_name":"John' .
                '","last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"ci' .
                'ty":"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"company_n' .
                'ame":"Fortis Payment Systems, LLC","header_message":"This is a sample message f' .
                'or you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333' .
                '9998822","office_phone":"3339998822","office_phone_ext":"5","home_phone_country' .
                '_code":"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","he' .
                'ader_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anyt' .
                'hing","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"' .
                'email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,' .
                '"created_user_id":"11e95f8ec39de8fbdb0a4f1a","received_emails":[{"subject":"Pay' .
                'ment Receipt - 12skiestech","body":"This email is being sent from a server.","s' .
                'ource_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path' .
                '":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67' .
                'bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_' .
                'model_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamste' .
                'r.com>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"is_deletable' .
                '":true,"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"mod' .
                'ified_ts":1422040992,"account_number":"5454545454545454","address":{"city":"Nov' .
                'i","state":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach":"' .
                '11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_' .
                'to":"email@domain.com","fax":"3339998822","location_api_id":"location-111111","' .
                'location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location' .
                '_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company Headquarte' .
                'rs","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"America/N' .
                'ew_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show' .
                '_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_typ' .
                'e":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"user":{"account_num' .
                'ber":"5454545454545454","branding_domain_url":"{branding_domain_url}","cell_pho' .
                'ne":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"3' .
                '339998822","first_name":"John","last_name":"Smith","locale":"en-US","office_pho' .
                'ne":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fb' .
                'db0a4f1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"' .
                'America/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_ex' .
                'port_type":"csv","process_method":"virtual_terminal","default_terminal":"11e95f' .
                '8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f92' .
                '3w2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","l' .
                'ocation_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_inv' .
                'itation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","cou' .
                'ntry":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"l' .
                'ast_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"crea' .
                'ted_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_a' .
                'gree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current' .
                '_login":1422040992,"log_api_response_body_ts":1422040992},"recurrings":[{"accou' .
                'nt_vault_id":"11e95f8ec39de8fbdb0a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'contact_id":"11e95f8ec39de8fbdb0a4f1a","account_vault_api_id":"token1234abcd","' .
                'token_api_id":"token1234abcd","_joi":{"conditions":{}},"active":true,"descripti' .
                'on":"Description","end_date":"2021-12-01","installment_total_count":20,"interva' .
                'l":1,"interval_type":"d","location_id":"11e95f8ec39de8fbdb0a4f1a","notification' .
                '_days":2,"payment_method":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring1234' .
                'abcd","start_date":"2021-12-01","status":"active","transaction_amount":300,"ter' .
                'ms_agree":true,"terms_agree_ip":"192.168.0.10","recurring_c1":"recurring custom' .
                ' data 1","recurring_c2":"recurring custom data 2","recurring_c3":"recurring cus' .
                'tom data 3","send_to_proc_as_recur":true,"tags":["Walk-in Customer"],"secondary' .
                '_amount":100,"currency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"' .
                '2021-12-01","created_ts":1422040992,"modified_ts":1422040992,"recurring_type_id' .
                '":"i","installment_amount_total":99999999,"created_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a"}],"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":tr' .
                'ue,"detail":true,"created_ts":1422040992},"sms_blacklist":{"id":"11e95f8ec39de8' .
                'fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":1422040992},"change' .
                'logs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREAT' .
                'E","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1' .
                'a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":' .
                '"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain' .
                '.com","first_name":"Bob","last_name":"Fairview"}}],"postback_logs":[{"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","postback_config_id":"11e95f8ec39de8fbdb0a4f1a","changelo' .
                'g_id":"11e95f8ec39de8fbdb0a4f1a","next_run_ts":1422040992,"created_ts":14220409' .
                '92,"model_id":"11e95f8ec39de8fbdb0a4f1a"}],"created_user":{"account_number":"54' .
                '54545454545454","branding_domain_url":"{branding_domain_url}","cell_phone":"333' .
                '9998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"333999882' .
                '2","first_name":"John","last_name":"Smith","locale":"en-US","office_phone":"333' .
                '9998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","requires_new_password":null,"terms_condition_code":"20220308","tz":"America/' .
                'New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_typ' .
                'e":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8' .
                'fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","us' .
                'er_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","location_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation"' .
                ':false,"address":{"city":"Novi","state":"MI","postal_code":"48375","country":"U' .
                'S"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_logi' .
                'n_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip"' .
                ':"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login":' .
                '1422040992,"log_api_response_body_ts":1422040992},"parent":{"location_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","fi' .
                'rst_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.36' .
                ',"address":{"city":"Novi","state":"Michigan","postal_code":"48375","country":"U' .
                'SA"},"company_name":"Fortis Payment Systems, LLC","header_message":"This is a s' .
                'ample message for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"h' .
                'ome_phone":"3339998822","office_phone":"3339998822","office_phone_ext":"5","hom' .
                'e_phone_country_code":"+1","office_phone_country_code":"+1","cell_phone_country' .
                '_code":"+1","header_message_type":0,"update_if_exists":1,"contact_c1":"any","co' .
                'ntact_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992' .
                ',"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"children":{"locat' .
                'ion_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_' .
                'id":"137","first_name":"John","last_name":"Smith","cell_phone":"3339998822","ba' .
                'lance":245.36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375"' .
                ',"country":"USA"},"company_name":"Fortis Payment Systems, LLC","header_message"' .
                ':"This is a sample message for you","date_of_birth":"2021-12-01","email_trx_rec' .
                'eipt":true,"home_phone":"3339998822","office_phone":"3339998822","office_phone_' .
                'ext":"5","home_phone_country_code":"+1","office_phone_country_code":"+1","cell_' .
                'phone_country_code":"+1","header_message_type":0,"update_if_exists":1,"contact_' .
                'c1":"any","contact_c2":"anything","contact_c3":"something","parent_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","email":"email@domain.com","token_import_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_t' .
                's":1422040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}}],"li' .
                'nks":{"type":"Links","first":"/v1/endpoint?page[size]=10&page[number]=1","previ' .
                'ous":"/v1/endpoint?page[size]=10&page[number]=5","next":"/v1/endpoint?page[size' .
                ']=10&page[number]=7","last":"/v1/endpoint?page[size]=10&page[number]=42"},"pagi' .
                'nation":{"type":"Pagination","total_count":423,"page_count":42,"page_number":6,' .
                '"page_size":10},"sort":{"type":"Sorting","fields":[{"field":"last_name","order"' .
                ':"asc"}]}}'
            )))
            ->assert();
    }

    public function testDeleteContact()
    {
        // Parameters for the API call
        $contactId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deleteContact($contactId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Contact","data":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_nu' .
                'mber":"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smi' .
                'th","cell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state"' .
                ':"Michigan","postal_code":"48375","country":"USA"},"company_name":"Fortis Payme' .
                'nt Systems, LLC","header_message":"This is a sample message for you","date_of_b' .
                'irth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_p' .
                'hone":"3339998822","office_phone_ext":"5","home_phone_country_code":"+1","offic' .
                'e_phone_country_code":"+1","cell_phone_country_code":"+1","header_message_type"' .
                ':0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3"' .
                ':"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com",' .
                '"token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'reated_ts":1422040992,"modified_ts":1422040992,"active":true,"created_user_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","received_emails":[{"subject":"Payment Receipt - 12s' .
                'kiestech","body":"This email is being sent from a server.","source_address":"' .
                '\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestec' .
                'h A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-' .
                '8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","rea' .
                'son_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11' .
                'e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"is_deletable":true,"location' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204' .
                '0992,"account_number":"5454545454545454","address":{"city":"Novi","state":"MI",' .
                '"postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e0' .
                '93242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domai' .
                'n.com","fax":"3339998822","location_api_id":"location-111111","location_api_key' .
                '":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2",' .
                '"location_c3":"custom data 3","name":"Sample Company Headquarters","office_phon' .
                'e":"2481234567","office_ext_phone":"1021021209","tz":"America/New_York","parent' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":' .
                'true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","t' .
                'icket_hash_key":"A5F443CADF4AE34BBCAADF4"},"user":{"account_number":"5454545454' .
                '545454","branding_domain_url":"{branding_domain_url}","cell_phone":"3339998822"' .
                ',"company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","ema' .
                'il":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998822","firs' .
                't_name":"John","last_name":"Smith","locale":"en-US","office_phone":"3339998822"' .
                ',"office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requi' .
                'res_new_password":null,"terms_condition_code":"20220308","tz":"America/New_York' .
                '","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv"' .
                ',"process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f' .
                '1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_' .
                'key":null,"user_type_code":100,"password":null,"zip":"48375","location_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"' .
                'address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":14' .
                '22040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.16' .
                '8.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login":14220409' .
                '92,"log_api_response_body_ts":1422040992},"recurrings":[{"account_vault_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contact_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","account_vault_api_id":"token1234abcd","token_api_id":"t' .
                'oken1234abcd","_joi":{"conditions":{}},"active":true,"description":"Description' .
                '","end_date":"2021-12-01","installment_total_count":20,"interval":1,"interval_t' .
                'ype":"d","location_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"paymen' .
                't_method":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_dat' .
                'e":"2021-12-01","status":"active","transaction_amount":300,"terms_agree":true,"' .
                'terms_agree_ip":"192.168.0.10","recurring_c1":"recurring custom data 1","recurr' .
                'ing_c2":"recurring custom data 2","recurring_c3":"recurring custom data 3","sen' .
                'd_to_proc_as_recur":true,"tags":["Walk-in Customer"],"secondary_amount":100,"cu' .
                'rrency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","cre' .
                'ated_ts":1422040992,"modified_ts":1422040992,"recurring_type_id":"i","installme' .
                'nt_amount_total":99999999,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email' .
                '_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true' .
                ',"created_ts":1422040992},"sms_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isB' .
                'lacklisted":true,"detail":true,"created_ts":1422040992},"changelogs":[{"id":"11' .
                'e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"Tran' .
                'sactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"' .
                'user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_nam' .
                'e":"Bob","last_name":"Fairview"}}],"postback_logs":[{"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","postback_config_id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","next_run_ts":1422040992,"created_ts":1422040992,"model_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a"}],"created_user":{"account_number":"5454545454545454",' .
                '"branding_domain_url":"{branding_domain_url}","cell_phone":"3339998822","compan' .
                'y_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"ema' .
                'il@domain.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":' .
                '"John","last_name":"Smith","locale":"en-US","office_phone":"3339998822","office' .
                '_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_' .
                'password":null,"terms_condition_code":"20220308","tz":"America/New_York","ui_pr' .
                'efs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv","proces' .
                's_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"us' .
                'ername":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":nul' .
                'l,"user_type_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"address"' .
                ':{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f' .
                '8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992' .
                ',"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10",' .
                '"current_date_time":"2019-03-11T10:38:26-0700","current_login":1422040992,"log_' .
                'api_response_body_ts":1422040992},"parent":{"location_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","account_number":"54545433332","contact_api_id":"137","first_name":"John"' .
                ',"last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"cit' .
                'y":"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"company_na' .
                'me":"Fortis Payment Systems, LLC","header_message":"This is a sample message fo' .
                'r you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339' .
                '998822","office_phone":"3339998822","office_phone_ext":"5","home_phone_country_' .
                'code":"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","hea' .
                'der_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anyth' .
                'ing","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"e' .
                'mail@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39' .
                'de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"' .
                'created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"children":{"location_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","first' .
                '_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.36,"a' .
                'ddress":{"city":"Novi","state":"Michigan","postal_code":"48375","country":"USA"' .
                '},"company_name":"Fortis Payment Systems, LLC","header_message":"This is a samp' .
                'le message for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home' .
                '_phone":"3339998822","office_phone":"3339998822","office_phone_ext":"5","home_p' .
                'hone_country_code":"+1","office_phone_country_code":"+1","cell_phone_country_co' .
                'de":"+1","header_message_type":0,"update_if_exists":1,"contact_c1":"any","conta' .
                'ct_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"a' .
                'ctive":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testListAllContacts()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllContacts(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"ContactsCollection","list":[{"location_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"account_number":"54545433332","contact_api_id":"137","first_name":"John","las' .
                't_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city":"N' .
                'ovi","state":"Michigan","postal_code":"48375","country":"USA"},"company_name":"' .
                'Fortis Payment Systems, LLC","header_message":"This is a sample message for you' .
                '","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999882' .
                '2","office_phone":"3339998822","office_phone_ext":"5","home_phone_country_code"' .
                ':"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","header_m' .
                'essage_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anything",' .
                '"contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@' .
                'domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"creat' .
                'ed_user_id":"11e95f8ec39de8fbdb0a4f1a","received_emails":[{"subject":"Payment R' .
                'eceipt - 12skiestech","body":"This email is being sent from a server.","source_' .
                'address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"' .
                '12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530' .
                '-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_model_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>' .
                '","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"is_deletable":true' .
                ',"location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_' .
                'ts":1422040992,"account_number":"5454545454545454","address":{"city":"Novi","st' .
                'ate":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608' .
                'a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"e' .
                'mail@domain.com","fax":"3339998822","location_api_id":"location-111111","locati' .
                'on_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"' .
                'custom 2","location_c3":"custom data 3","name":"Sample Company Headquarters","o' .
                'ffice_phone":"2481234567","office_ext_phone":"1021021209","tz":"America/New_Yor' .
                'k","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_conta' .
                'ct_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"me' .
                'rchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"user":{"account_number":"' .
                '5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone":"3' .
                '339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998' .
                '822","first_name":"John","last_name":"Smith","locale":"en-US","office_phone":"3' .
                '339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"Americ' .
                'a/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_t' .
                'ype":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39d' .
                'e8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","' .
                'user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","locatio' .
                'n_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitatio' .
                'n":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","country":' .
                '"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_lo' .
                'gin_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_i' .
                'p":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login' .
                '":1422040992,"log_api_response_body_ts":1422040992},"recurrings":[{"account_vau' .
                'lt_id":"11e95f8ec39de8fbdb0a4f1a","token_id":"11e95f8ec39de8fbdb0a4f1a","contac' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","account_vault_api_id":"token1234abcd","token_' .
                'api_id":"token1234abcd","_joi":{"conditions":{}},"active":true,"description":"D' .
                'escription","end_date":"2021-12-01","installment_total_count":20,"interval":1,"' .
                'interval_type":"d","location_id":"11e95f8ec39de8fbdb0a4f1a","notification_days"' .
                ':2,"payment_method":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","r' .
                'ecurring_id":"11e95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring1234abcd",' .
                '"start_date":"2021-12-01","status":"active","transaction_amount":300,"terms_agr' .
                'ee":true,"terms_agree_ip":"192.168.0.10","recurring_c1":"recurring custom data ' .
                '1","recurring_c2":"recurring custom data 2","recurring_c3":"recurring custom da' .
                'ta 3","send_to_proc_as_recur":true,"tags":["Walk-in Customer"],"secondary_amoun' .
                't":100,"currency":"USD","id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-1' .
                '2-01","created_ts":1422040992,"modified_ts":1422040992,"recurring_type_id":"i",' .
                '"installment_amount_total":99999999,"created_user_id":"11e95f8ec39de8fbdb0a4f1a' .
                '"}],"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"de' .
                'tail":true,"created_ts":1422040992},"sms_blacklist":{"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","isBlacklisted":true,"detail":true,"created_ts":1422040992},"changelogs":' .
                '[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","mo' .
                'del":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","ch' .
                'angelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"16436' .
                '16000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com",' .
                '"first_name":"Bob","last_name":"Fairview"}}],"postback_logs":[{"id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","postback_config_id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","next_run_ts":1422040992,"created_ts":1422040992,"mo' .
                'del_id":"11e95f8ec39de8fbdb0a4f1a"}],"created_user":{"account_number":"54545454' .
                '54545454","branding_domain_url":"{branding_domain_url}","cell_phone":"333999882' .
                '2","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","e' .
                'mail":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998822","fi' .
                'rst_name":"John","last_name":"Smith","locale":"en-US","office_phone":"333999882' .
                '2","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","req' .
                'uires_new_password":null,"terms_condition_code":"20220308","tz":"America/New_Yo' .
                'rk","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type":"cs' .
                'v","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a' .
                '4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_has' .
                'h_key":null,"user_type_code":100,"password":null,"zip":"48375","location_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false' .
                ',"address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":' .
                '1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.' .
                '168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login":142204' .
                '0992,"log_api_response_body_ts":1422040992},"parent":{"location_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","first_na' .
                'me":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.36,"addr' .
                'ess":{"city":"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"' .
                'company_name":"Fortis Payment Systems, LLC","header_message":"This is a sample ' .
                'message for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_ph' .
                'one":"3339998822","office_phone":"3339998822","office_phone_ext":"5","home_phon' .
                'e_country_code":"+1","office_phone_country_code":"+1","cell_phone_country_code"' .
                ':"+1","header_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_' .
                'c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"acti' .
                've":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"children":{"location_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"1' .
                '37","first_name":"John","last_name":"Smith","cell_phone":"3339998822","balance"' .
                ':245.36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375","coun' .
                'try":"USA"},"company_name":"Fortis Payment Systems, LLC","header_message":"This' .
                ' is a sample message for you","date_of_birth":"2021-12-01","email_trx_receipt":' .
                'true,"home_phone":"3339998822","office_phone":"3339998822","office_phone_ext":"' .
                '5","home_phone_country_code":"+1","office_phone_country_code":"+1","cell_phone_' .
                'country_code":"+1","header_message_type":0,"update_if_exists":1,"contact_c1":"a' .
                'ny","contact_c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}}],"links":{' .
                '"type":"Links","first":"/v1/endpoint?page[size]=10&page[number]=1","previous":"' .
                '/v1/endpoint?page[size]=10&page[number]=5","next":"/v1/endpoint?page[size]=10&p' .
                'age[number]=7","last":"/v1/endpoint?page[size]=10&page[number]=42"},"pagination' .
                '":{"type":"Pagination","total_count":423,"page_count":42,"page_number":6,"page_' .
                'size":10},"sort":{"type":"Sorting","fields":[{"field":"last_name","order":"asc"' .
                '}]}}'
            )))
            ->assert();
    }
}
