<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\LocationsController;
use FortisAPILib\Exceptions;
use FortisAPILib\Models;

class LocationsControllerTest extends BaseTestController
{
    /**
     * @var LocationsController LocationsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getLocationsController();
    }

    public function testListAllLocations()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllLocations(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"LocationsCollection","list":[{"id":"11e95f8ec39de8fbdb0a4f1a","create' .
                'd_ts":1422040992,"modified_ts":1422040992,"account_number":"5454545454545454","' .
                'address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"bra' .
                'nding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default"' .
                ':true,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092' .
                '242dda","email_reply_to":"email@domain.com","fax":"3339998822","location_api_id' .
                '":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1"' .
                ':"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Samp' .
                'le Company Headquarters","office_phone":"2481234567","office_ext_phone":"102102' .
                '1209","tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_cont' .
                'act_notes":true,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","location_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4",' .
                '"parent":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts"' .
                ':1422040992,"account_number":"5454545454545454","address":{"city":"Novi","state' .
                '":"MI","postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d' .
                '515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"emai' .
                'l@domain.com","fax":"3339998822","location_api_id":"location-111111","location_' .
                'api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"cus' .
                'tom 2","location_c3":"custom data 3","name":"Sample Company Headquarters","offi' .
                'ce_phone":"2481234567","office_ext_phone":"1021021209","tz":"America/New_York",' .
                '"parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_' .
                'files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merch' .
                'ant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"users":[{"account_number":"5' .
                '454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone":"33' .
                '39998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"33399988' .
                '22","first_name":"John","last_name":"Smith","locale":"en-US","office_phone":"33' .
                '39998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","requires_new_password":null,"terms_condition_code":"20220308","tz":"America' .
                '/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_ty' .
                'pe":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de' .
                '8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","u' .
                'ser_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","location' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation' .
                '":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","country":"' .
                'US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_log' .
                'in_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_use' .
                'r_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip' .
                '":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login"' .
                ':1422040992,"log_api_response_body_ts":1422040992}],"is_deletable":true,"termin' .
                'als":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","default_product_transaction_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","terminal_application_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","terminal_cvm_id":"11e95f8ec39de8fbdb0a4f1a","terminal_manufacturer_code":"1' .
                '","title":"My terminal","mac_address":"3D:F2:C9:A6:B3:4F","local_ip_address":"1' .
                '92.168.0.10","port":10009,"serial_number":"1234567890","terminal_number":"97345' .
                '6789012367","terminal_timeouts":{"card_entry_timeout":47,"device_terms_prompt_t' .
                'imeout":30,"overall_timeout":125,"pin_entry_timeout":40,"signature_input_timeou' .
                't":35,"signature_submit_timeout":38,"status_display_time":12,"tip_cashback_time' .
                'out":25,"transaction_timeout":17},"tip_percents":{"percent_1":0,"percent_2":2,"' .
                'percent_3":99},"header_line_1":"line 1 sample","header_line_2":"line 2 sample",' .
                '"header_line_3":"line 3 sample","header_line_4":"line 4 sample","header_line_5"' .
                ':"line 5 sample","trailer_line_1":"trailer 1 sample","trailer_line_2":"trailer ' .
                '2 sample","trailer_line_3":"trailer 3 sample","trailer_line_4":"trailer 4 sampl' .
                'e","trailer_line_5":"trailer 5 sample","default_checkin":"2021-12-01","default_' .
                'checkout":"2021-12-01","default_room_rate":56,"default_room_number":"303","debi' .
                't":false,"emv":false,"cashback_enable":false,"print_enable":false,"sig_capture_' .
                'enable":false,"is_provisioned":false,"tip_enable":false,"validated_decryption":' .
                'false,"communication_type":"http","active":true,"id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"created_ts":1422040992,"modified_ts":1422040992,"last_registration_ts":142204' .
                '0992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec' .
                '39de8fbdb0a4f1a"}],"branding_domain":{"url":"fortispayrbyn9y.sandbox.zeamster.c' .
                'om","title":"Test Brand Domain Title 2","logo":"","support_email":"email@domain' .
                '.com","allow_contact_signup":true,"allow_contact_registration":true,"allow_cont' .
                'act_login":true,"registration_fields":["account_number"],"company_name":null,"n' .
                'av_color":null,"button_primary_color":null,"logo_background_color":null,"icon_b' .
                'ackground_color":null,"menu_text_background_color":null,"menu_text_color":null,' .
                '"right_menu_background_color":null,"right_menu_text_color":null,"button_primary' .
                '_text_color":null,"nav_logo":null,"fav_icon":null,"aes_key":null,"help_text":nu' .
                'll,"email_reply_to":"email@domain.com","email":"email@domain.com","custom_javas' .
                'cript":null,"custom_theme":null,"custom_css":null,"contact_user_default_entry_p' .
                'age":"dashboard","contact_user_default_auth_roles":[null],"custom_stylesheet_ur' .
                'l":"https://127.0.0.1/receiver","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14' .
                '22040992,"modified_ts":1422040992},"product_invoice":{"title":"Sample title","q' .
                'uote_number_start":1,"quote_number_increment":1,"quote_number_current":1,"invoi' .
                'ce_number_start":1,"invoice_number_increment":1,"invoice_number_current":1,"tax' .
                '_rate":0,"tax_fee":0,"monthly_fee":0,"per_invoice_fee":0,"per_quote_fee":0,"req' .
                'uire_pay_in_full":true,"selectable":1,"reportable":1,"portfolio_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","location_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"produc' .
                't_files":[{"title":"My terminal","product_file_credential_id":"11e95f8ec39de8fb' .
                'db0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts"' .
                ':1422040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"creat' .
                'ed_user":{"account_number":"5454545454545454","branding_domain_url":"{branding_' .
                'domain_url}","cell_phone":"3339998822","company_name":"Fortis Payment Systems, ' .
                'LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","doma' .
                'in_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt' .
                '":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith","local' .
                'e":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_location' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condition_c' .
                'ode":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard","p' .
                'age_size":2,"report_export_type":"csv","process_method":"virtual_terminal","def' .
                'ault_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_k' .
                'ey":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"password"' .
                ':null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"a' .
                'pi_only":false,"is_invitation":false,"address":{"city":"Novi","state":"MI","pos' .
                'tal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true' .
                ',"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modifie' .
                'd_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_t' .
                's":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T1' .
                '0:38:26-0700","current_login":1422040992,"log_api_response_body_ts":1422040992}' .
                ',"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action' .
                '":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","' .
                'user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8f' .
                'bdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old' .
                '_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"emai' .
                'l@domain.com","first_name":"Bob","last_name":"Fairview"}}],"product_transaction' .
                's":[{"processor_version":"1_0_0","title":"My terminal","payment_method":"cc","p' .
                'rocessor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"standalone",' .
                '"location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt' .
                '_clerk_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allow_deb' .
                'it":true,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt_stre' .
                'et":true,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receipt_show_conta' .
                'ct_name":true,"display_avs":true,"card_type_visa":true,"card_type_mc":true,"car' .
                'd_type_disc":true,"card_type_amex":true,"card_type_diners":true,"card_type_jcb"' .
                ':true,"card_type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_stamp"' .
                ':true,"invoice_location":true,"allow_partial_authorization":true,"allow_recurri' .
                'ng_partial_authorization":true,"auto_decline_cvv":true,"auto_decline_street":tr' .
                'ue,"auto_decline_zip":true,"split_payments_allow":true,"vt_show_custom_fields":' .
                'true,"receipt_show_custom_fields":true,"vt_override_sales_tax_allowed":true,"vt' .
                '_enable_sales_tax":true,"vt_require_zip":true,"vt_require_street":true,"auto_de' .
                'cline_cavv":true,"current_batch":34,"dup_check_per_batch":null,"paylink_allow":' .
                'false,"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":false,"e' .
                'nable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_p' .
                'age_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce"' .
                ':false,"level3_default":{"destination_country_code":"840","duty_amount":0,"frei' .
                'ght_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ12345","s' .
                'hipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_registr' .
                'ation":"12345678","merchant_vat_registration":"123456","order_date":"171006","s' .
                'ummary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","l' .
                'ine_items":[{"alternate_tax_id":"1234","debit_credit":"C","description":"cool d' .
                'rink","discount_amount":10,"discount_rate":11,"product_code":"coke12345678","qu' .
                'antity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id":"a1' .
                '","unit_code":"gll","unit_cost":10,"commodity_code":"cc123456","other_tax_amoun' .
                't":0}]},"cau_subscribe_type_id":0,"location_billing_account_id":"11eb88b873980c' .
                '64a21e5fd2","product_billing_group_id":"nofees","account_number":"12345678","ru' .
                'n_avs_on_accountvault_create":false,"accountvault_expire_notification_email_ena' .
                'ble":false,"debit_allow_void":false,"quick_invoice_text_to_pay":false,"sms_enab' .
                'le":false,"vt_show_currency":true,"receipt_show_currency":false,"allow_blind_re' .
                'fund":false,"vt_show_company_name":false,"receipt_show_company_name":false,"ban' .
                'k_funded_only":false,"require_cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_' .
                'cnp":true,"show_secondary_amount":false,"allow_secondary_amount":false,"show_go' .
                'ogle_pay":true,"show_apple_pay":true,"batch_risk_config":{},"currency_code":840' .
                ',"enable_ach_validation":false,"enable_ach_retry":false,"id":"11e95f8ec39de8fbd' .
                'b0a4f1a","active":true,"created_ts":1422040992,"modified_ts":1422040992,"create' .
                'd_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amou' .
                'nt_allowed":false,"fortis_id":"8149742","product_billing_group_code":"nofees","' .
                'cau_subscribe_type_code":0}],"terminal_routers":[{"mac_address":"3D:F2:C9:A6:B3' .
                ':4F","location_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","' .
                'created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a"}],"developer_company":{"title":"My terminal","id":"11e95f8ec39de8' .
                'fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":1422040992,"cre' .
                'ated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a"},"developer_company_id":"sample developer company id","helppages":[{"us' .
                'er_type_code":100,"body":"Sample Body","title":"Sample Title","id":"11e95f8ec39' .
                'de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"' .
                'quick_invoice_setting":{"location_api_id":"11e95f8ec39de8fbdb0a4f1a","location_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","quick_invoice_template":"<html>Template<html>",' .
                '"default_allow_partial_pay":true,"default_notification_on_due_date":true,"defau' .
                'lt_notification_days_after_due_date":7,"default_notification_days_before_due_da' .
                'te":3,"show_custom_fields":false,"id":"11e95f8ec39de8fbdb0a4f1a"},"location_bil' .
                'ling_accounts":[{"title":"Billing Acccount Title","location_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","ach_sec_code":null,"account_number":null,"routing":null,"exp_date"' .
                ':"0722","billing_zip":"48375","account_type":null,"account_holder_name":"John S' .
                'mith","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","billing_descriptor":null,"payment_method":null,"portfolio_' .
                'id":"11e95f8ec39de8fbdb0a4f1a"}],"marketplaces":[{"location_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","marketplace_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,' .
                '"user_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_t' .
                's":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"locationmarketpla' .
                'ces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","marketplace_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","location_api_id":null,"user_id":"11e95f8ec39de8fbdb0a4f1a","id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a"}],"addons":[{"title":" ","secret":" ","iframe_url":" ","locatio' .
                'n_setup_url":" ","user_setup_url":" ","encrypt_url_params":true}]}],"links":{"t' .
                'ype":"Links","first":"/v1/endpoint?page[size]=10&page[number]=1","previous":"/v' .
                '1/endpoint?page[size]=10&page[number]=5","next":"/v1/endpoint?page[size]=10&pag' .
                'e[number]=7","last":"/v1/endpoint?page[size]=10&page[number]=42"},"pagination":' .
                '{"type":"Pagination","total_count":423,"page_count":42,"page_number":6,"page_si' .
                'ze":10},"sort":{"type":"Sorting","fields":[{"field":"last_name","order":"asc"}]' .
                '}}'
            )))
            ->assert();
    }

    public function testLocationsDetail()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;
        $productTransactionActive =
            null;
        $productFileActive =
            null;
        $productInvoiceActive =
            null;
        $productRecurringActive =
            null;
        $productAccountvaultActive =
            null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->locationsDetail(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields,
                $productTransactionActive,
                $productFileActive,
                $productInvoiceActive,
                $productRecurringActive,
                $productAccountvaultActive
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"LocationInfosCollection","list":[{"id":"11e95f8ec39de8fbdb0a4f1a","cr' .
                'eated_ts":1422040992,"modified_ts":1422040992,"account_number":"545454545454545' .
                '4","address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},' .
                '"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_defa' .
                'ult":true,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1' .
                'e092242dda","email_reply_to":"email@domain.com","fax":"3339998822","location_ap' .
                'i_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location' .
                '_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name":"' .
                'Sample Company Headquarters","office_phone":"2481234567","office_ext_phone":"10' .
                '21021209","tz":"America/New_York","parent_id":"11ed3e73adb98c0282f3fa9b","show_' .
                'contact_notes":true,"show_contact_files":true,"created_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","location_type":"merchant","branding_domain_url":"subdomain.sandbox' .
                '.domain.com","branding_domain":{"url":"fortispayrbyn9y.sandbox.zeamster.com","t' .
                'itle":"Test Brand Domain Title 2","logo":"","support_email":"email@domain.com",' .
                '"allow_contact_signup":true,"allow_contact_registration":true,"allow_contact_lo' .
                'gin":true,"registration_fields":["account_number"],"company_name":null,"nav_col' .
                'or":null,"button_primary_color":null,"logo_background_color":null,"icon_backgro' .
                'und_color":null,"menu_text_background_color":null,"menu_text_color":null,"right' .
                '_menu_background_color":null,"right_menu_text_color":null,"button_primary_text_' .
                'color":null,"nav_logo":null,"fav_icon":null,"aes_key":null,"help_text":null,"em' .
                'ail_reply_to":"email@domain.com","email":"email@domain.com","custom_javascript"' .
                ':null,"custom_theme":null,"custom_css":null,"contact_user_default_entry_page":"' .
                'dashboard","contact_user_default_auth_roles":[null],"custom_stylesheet_url":"ht' .
                'tps://127.0.0.1/receiver","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"modified_ts":1422040992},"product_transactions":[{"processor_version":"1_0_' .
                '0","title":"My terminal","payment_method":"cc","processor":"zgate","mcc":"1111"' .
                ',"tax_surcharge_config":2,"partner":"standalone","location_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","surcharge":{},"processor_data":{},"vt_clerk_number":true,"vt_billin' .
                'g_phone":true,"vt_enable_tip":true,"ach_allow_debit":true,"ach_allow_credit":tr' .
                'ue,"ach_allow_refund":true,"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_ord' .
                'er_num":true,"vt_enable":true,"receipt_show_contact_name":true,"display_avs":tr' .
                'ue,"card_type_visa":true,"card_type_mc":true,"card_type_disc":true,"card_type_a' .
                'mex":true,"card_type_diners":true,"card_type_jcb":true,"card_type_ebt":true,"al' .
                'low_ebt_cash_benefit":true,"allow_ebt_food_stamp":true,"invoice_location":true,' .
                '"allow_partial_authorization":true,"allow_recurring_partial_authorization":true' .
                ',"auto_decline_cvv":true,"auto_decline_street":true,"auto_decline_zip":true,"sp' .
                'lit_payments_allow":true,"vt_show_custom_fields":true,"receipt_show_custom_fiel' .
                'ds":true,"vt_override_sales_tax_allowed":true,"vt_enable_sales_tax":true,"vt_re' .
                'quire_zip":true,"vt_require_street":true,"auto_decline_cavv":true,"current_batc' .
                'h":34,"dup_check_per_batch":null,"paylink_allow":false,"quick_invoice_allow":fa' .
                'lse,"level3_allow":false,"payfac_enable":false,"enable_3ds":false,"sales_office' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,"surcharge_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce":false,"level3_default":{"dest' .
                'ination_country_code":"840","duty_amount":0,"freight_amount":0,"national_tax":2' .
                ',"sales_tax":200,"shipfrom_zip_code":"AZ12345","shipto_zip_code":"MI48335","tax' .
                '_amount":0,"tax_exempt":"0","customer_vat_registration":"12345678","merchant_va' .
                't_registration":"123456","order_date":"171006","summary_commodity_code":"C1K2",' .
                '"tax_rate":0,"unique_vat_ref_number":"vat1234","line_items":[{"alternate_tax_id' .
                '":"1234","debit_credit":"C","description":"cool drink","discount_amount":10,"di' .
                'scount_rate":11,"product_code":"coke12345678","quantity":5,"tax_amount":3,"tax_' .
                'rate":0,"tax_type_applied":"22","tax_type_id":"a1","unit_code":"gll","unit_cost' .
                '":10,"commodity_code":"cc123456","other_tax_amount":0}]},"cau_subscribe_type_id' .
                '":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","product_billing_g' .
                'roup_id":"nofees","account_number":"12345678","run_avs_on_accountvault_create":' .
                'false,"accountvault_expire_notification_email_enable":false,"debit_allow_void":' .
                'false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_show_currency":t' .
                'rue,"receipt_show_currency":false,"allow_blind_refund":false,"vt_show_company_n' .
                'ame":false,"receipt_show_company_name":false,"bank_funded_only":false,"require_' .
                'cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_cnp":true,"show_secondary_amou' .
                'nt":false,"allow_secondary_amount":false,"show_google_pay":true,"show_apple_pay' .
                '":true,"batch_risk_config":{},"currency_code":840,"enable_ach_validation":false' .
                ',"enable_ach_retry":false,"id":"11e95f8ec39de8fbdb0a4f1a","active":true,"create' .
                'd_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_api_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_allowed":false,"fortis_id":' .
                '"8149742","product_billing_group_code":"nofees","cau_subscribe_type_code":0}],"' .
                'product_file":{"title":"My terminal","product_file_credential_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified' .
                '_ts":1422040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"pr' .
                'oduct_accountvault":{"title":"My terminal","location_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"mod' .
                'ified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_use' .
                'r_id":"11e95f8ec39de8fbdb0a4f1a"},"product_token":{"title":"My terminal","locat' .
                'ion_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","active":tru' .
                'e,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"product_recurr' .
                'ing":{"title":"Fortispay RbYN6y","location_id":"11e95f8ec39de8fbdb0a4f1a","loca' .
                'tion_api_id":"11e95f8ec39de8fbdb0a4f1a","send_declined_notifications":true,"req' .
                'uire_full_payment":true,"expire_notification_email_enable":true,"expire_notific' .
                'ation_sms_enable":true,"notification_days_default":1,"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"tags":[{"l' .
                'ocation_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"terminals":[{' .
                '"location_id":"11e95f8ec39de8fbdb0a4f1a","default_product_transaction_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","terminal_application_id":"11e95f8ec39de8fbdb0a4f1a","ter' .
                'minal_cvm_id":"11e95f8ec39de8fbdb0a4f1a","terminal_manufacturer_code":"1","titl' .
                'e":"My terminal","mac_address":"3D:F2:C9:A6:B3:4F","local_ip_address":"192.168.' .
                '0.10","port":10009,"serial_number":"1234567890","terminal_number":"973456789012' .
                '367","terminal_timeouts":{"card_entry_timeout":47,"device_terms_prompt_timeout"' .
                ':30,"overall_timeout":125,"pin_entry_timeout":40,"signature_input_timeout":35,"' .
                'signature_submit_timeout":38,"status_display_time":12,"tip_cashback_timeout":25' .
                ',"transaction_timeout":17},"tip_percents":{"percent_1":0,"percent_2":2,"percent' .
                '_3":99},"header_line_1":"line 1 sample","header_line_2":"line 2 sample","header' .
                '_line_3":"line 3 sample","header_line_4":"line 4 sample","header_line_5":"line ' .
                '5 sample","trailer_line_1":"trailer 1 sample","trailer_line_2":"trailer 2 sampl' .
                'e","trailer_line_3":"trailer 3 sample","trailer_line_4":"trailer 4 sample","tra' .
                'iler_line_5":"trailer 5 sample","default_checkin":"2021-12-01","default_checkou' .
                't":"2021-12-01","default_room_rate":56,"default_room_number":"303","debit":fals' .
                'e,"emv":false,"cashback_enable":false,"print_enable":false,"sig_capture_enable"' .
                ':false,"is_provisioned":false,"tip_enable":false,"validated_decryption":false,"' .
                'communication_type":"http","active":true,"id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"last_registration_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a"}]}],"links":{"type":"Links","first":"/v1/endpoint?page[size]=10&page[' .
                'number]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","next":"/v1/e' .
                'ndpoint?page[size]=10&page[number]=7","last":"/v1/endpoint?page[size]=10&page[n' .
                'umber]=42"},"pagination":{"type":"Pagination","total_count":423,"page_count":42' .
                ',"page_number":6,"page_size":10},"sort":{"type":"Sorting","fields":[{"field":"l' .
                'ast_name","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testLocationDetail()
    {
        // Parameters for the API call
        $locationId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;
        $productTransactionActive =
            null;
        $productFileActive =
            null;
        $productInvoiceActive =
            null;
        $productRecurringActive =
            null;
        $productAccountvaultActive =
            null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->locationDetail(
                $locationId,
                $expand,
                $fields,
                $productTransactionActive,
                $productFileActive,
                $productInvoiceActive,
                $productRecurringActive,
                $productAccountvaultActive
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"LocationInfo","data":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14' .
                '22040992,"modified_ts":1422040992,"account_number":"5454545454545454","address"' .
                ':{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_do' .
                'main_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"d' .
                'efault_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda",' .
                '"email_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"locat' .
                'ion-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom' .
                ' 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Sample Compa' .
                'ny Headquarters","office_phone":"2481234567","office_ext_phone":"1021021209","t' .
                'z":"America/New_York","parent_id":"11ed3e73adb98c0282f3fa9b","show_contact_note' .
                's":true,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"location_type":"merchant","branding_domain_url":"subdomain.sandbox.domain.com"' .
                ',"branding_domain":{"url":"fortispayrbyn9y.sandbox.zeamster.com","title":"Test ' .
                'Brand Domain Title 2","logo":"","support_email":"email@domain.com","allow_conta' .
                'ct_signup":true,"allow_contact_registration":true,"allow_contact_login":true,"r' .
                'egistration_fields":["account_number"],"company_name":null,"nav_color":null,"bu' .
                'tton_primary_color":null,"logo_background_color":null,"icon_background_color":n' .
                'ull,"menu_text_background_color":null,"menu_text_color":null,"right_menu_backgr' .
                'ound_color":null,"right_menu_text_color":null,"button_primary_text_color":null,' .
                '"nav_logo":null,"fav_icon":null,"aes_key":null,"help_text":null,"email_reply_to' .
                '":"email@domain.com","email":"email@domain.com","custom_javascript":null,"custo' .
                'm_theme":null,"custom_css":null,"contact_user_default_entry_page":"dashboard","' .
                'contact_user_default_auth_roles":[null],"custom_stylesheet_url":"https://127.0.' .
                '0.1/receiver","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified' .
                '_ts":1422040992},"product_transactions":[{"processor_version":"1_0_0","title":"' .
                'My terminal","payment_method":"cc","processor":"zgate","mcc":"1111","tax_surcha' .
                'rge_config":2,"partner":"standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'surcharge":{},"processor_data":{},"vt_clerk_number":true,"vt_billing_phone":tru' .
                'e,"vt_enable_tip":true,"ach_allow_debit":true,"ach_allow_credit":true,"ach_allo' .
                'w_refund":true,"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_order_num":true' .
                ',"vt_enable":true,"receipt_show_contact_name":true,"display_avs":true,"card_typ' .
                'e_visa":true,"card_type_mc":true,"card_type_disc":true,"card_type_amex":true,"c' .
                'ard_type_diners":true,"card_type_jcb":true,"card_type_ebt":true,"allow_ebt_cash' .
                '_benefit":true,"allow_ebt_food_stamp":true,"invoice_location":true,"allow_parti' .
                'al_authorization":true,"allow_recurring_partial_authorization":true,"auto_decli' .
                'ne_cvv":true,"auto_decline_street":true,"auto_decline_zip":true,"split_payments' .
                '_allow":true,"vt_show_custom_fields":true,"receipt_show_custom_fields":true,"vt' .
                '_override_sales_tax_allowed":true,"vt_enable_sales_tax":true,"vt_require_zip":t' .
                'rue,"vt_require_street":true,"auto_decline_cavv":true,"current_batch":34,"dup_c' .
                'heck_per_batch":null,"paylink_allow":false,"quick_invoice_allow":false,"level3_' .
                'allow":false,"payfac_enable":false,"enable_3ds":false,"sales_office_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,"surcharge_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","allow_big_commerce":false,"level3_default":{"destination_coun' .
                'try_code":"840","duty_amount":0,"freight_amount":0,"national_tax":2,"sales_tax"' .
                ':200,"shipfrom_zip_code":"AZ12345","shipto_zip_code":"MI48335","tax_amount":0,"' .
                'tax_exempt":"0","customer_vat_registration":"12345678","merchant_vat_registrati' .
                'on":"123456","order_date":"171006","summary_commodity_code":"C1K2","tax_rate":0' .
                ',"unique_vat_ref_number":"vat1234","line_items":[{"alternate_tax_id":"1234","de' .
                'bit_credit":"C","description":"cool drink","discount_amount":10,"discount_rate"' .
                ':11,"product_code":"coke12345678","quantity":5,"tax_amount":3,"tax_rate":0,"tax' .
                '_type_applied":"22","tax_type_id":"a1","unit_code":"gll","unit_cost":10,"commod' .
                'ity_code":"cc123456","other_tax_amount":0}]},"cau_subscribe_type_id":0,"locatio' .
                'n_billing_account_id":"11eb88b873980c64a21e5fd2","product_billing_group_id":"no' .
                'fees","account_number":"12345678","run_avs_on_accountvault_create":false,"accou' .
                'ntvault_expire_notification_email_enable":false,"debit_allow_void":false,"quick' .
                '_invoice_text_to_pay":false,"sms_enable":false,"vt_show_currency":true,"receipt' .
                '_show_currency":false,"allow_blind_refund":false,"vt_show_company_name":false,"' .
                'receipt_show_company_name":false,"bank_funded_only":false,"require_cvv_on_keyed' .
                '_cnp":true,"require_cvv_on_tokenized_cnp":true,"show_secondary_amount":false,"a' .
                'llow_secondary_amount":false,"show_google_pay":true,"show_apple_pay":true,"batc' .
                'h_risk_config":{},"currency_code":840,"enable_ach_validation":false,"enable_ach' .
                '_retry":false,"id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":142204' .
                '0992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","mod' .
                'ified_user_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_api_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","is_secondary_amount_allowed":false,"fortis_id":"8149742","p' .
                'roduct_billing_group_code":"nofees","cau_subscribe_type_code":0}],"product_file' .
                '":{"title":"My terminal","product_file_credential_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040' .
                '992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"product_accoun' .
                'tvault":{"title":"My terminal","location_id":"11e95f8ec39de8fbdb0a4f1a","id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":14' .
                '22040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95' .
                'f8ec39de8fbdb0a4f1a"},"product_token":{"title":"My terminal","location_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_t' .
                's":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"product_recurring":{"title' .
                '":"Fortispay RbYN6y","location_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","send_declined_notifications":true,"require_full_pa' .
                'yment":true,"expire_notification_email_enable":true,"expire_notification_sms_en' .
                'able":true,"notification_days_default":1,"id":"11e95f8ec39de8fbdb0a4f1a","creat' .
                'ed_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"tags":[{"location_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a' .
                '","created_ts":1422040992,"modified_ts":1422040992}],"terminals":[{"location_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","default_product_transaction_id":"11e95f8ec39de8fb' .
                'db0a4f1a","terminal_application_id":"11e95f8ec39de8fbdb0a4f1a","terminal_cvm_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","terminal_manufacturer_code":"1","title":"My termi' .
                'nal","mac_address":"3D:F2:C9:A6:B3:4F","local_ip_address":"192.168.0.10","port"' .
                ':10009,"serial_number":"1234567890","terminal_number":"973456789012367","termin' .
                'al_timeouts":{"card_entry_timeout":47,"device_terms_prompt_timeout":30,"overall' .
                '_timeout":125,"pin_entry_timeout":40,"signature_input_timeout":35,"signature_su' .
                'bmit_timeout":38,"status_display_time":12,"tip_cashback_timeout":25,"transactio' .
                'n_timeout":17},"tip_percents":{"percent_1":0,"percent_2":2,"percent_3":99},"hea' .
                'der_line_1":"line 1 sample","header_line_2":"line 2 sample","header_line_3":"li' .
                'ne 3 sample","header_line_4":"line 4 sample","header_line_5":"line 5 sample","t' .
                'railer_line_1":"trailer 1 sample","trailer_line_2":"trailer 2 sample","trailer_' .
                'line_3":"trailer 3 sample","trailer_line_4":"trailer 4 sample","trailer_line_5"' .
                ':"trailer 5 sample","default_checkin":"2021-12-01","default_checkout":"2021-12-' .
                '01","default_room_rate":56,"default_room_number":"303","debit":false,"emv":fals' .
                'e,"cashback_enable":false,"print_enable":false,"sig_capture_enable":false,"is_p' .
                'rovisioned":false,"tip_enable":false,"validated_decryption":false,"communicatio' .
                'n_type":"http","active":true,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220' .
                '40992,"modified_ts":1422040992,"last_registration_ts":1422040992,"created_user_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}]}' .
                '}'
            )))
            ->assert();
    }

    public function testLocationsSearch()
    {
        // Parameters for the API call
        $page = null;
        $keyword = null;
        $relationship = Models\RelationshipEnum::CHILD;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->locationsSearch($page, $keyword, $relationship);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"LocationSearchsCollection","list":[{"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'created_ts":1422040992,"modified_ts":1422040992,"account_number":"5454545454545' .
                '454","address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"' .
                '},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_de' .
                'fault":true,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5' .
                'f1e092242dda","email_reply_to":"email@domain.com","fax":"3339998822","location_' .
                'api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","locati' .
                'on_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name"' .
                ':"Sample Company Headquarters","office_phone":"2481234567","office_ext_phone":"' .
                '1021021209","tz":"America/New_York","parent_id":"11ed3e73adb98c0282f3fa9b","sho' .
                'w_contact_notes":true,"show_contact_files":true,"created_user_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","location_type":"merchant","branding_domain_url":"subdomain.sandb' .
                'ox.domain.com","branding_domain":{"url":"fortispayrbyn9y.sandbox.zeamster.com",' .
                '"title":"Test Brand Domain Title 2","logo":"","support_email":"email@domain.com' .
                '","allow_contact_signup":true,"allow_contact_registration":true,"allow_contact_' .
                'login":true,"registration_fields":["account_number"],"company_name":null,"nav_c' .
                'olor":null,"button_primary_color":null,"logo_background_color":null,"icon_backg' .
                'round_color":null,"menu_text_background_color":null,"menu_text_color":null,"rig' .
                'ht_menu_background_color":null,"right_menu_text_color":null,"button_primary_tex' .
                't_color":null,"nav_logo":null,"fav_icon":null,"aes_key":null,"help_text":null,"' .
                'email_reply_to":"email@domain.com","email":"email@domain.com","custom_javascrip' .
                't":null,"custom_theme":null,"custom_css":null,"contact_user_default_entry_page"' .
                ':"dashboard","contact_user_default_auth_roles":[null],"custom_stylesheet_url":"' .
                'https://127.0.0.1/receiver","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204' .
                '0992,"modified_ts":1422040992},"product_transactions":[{"processor_version":"1_' .
                '0_0","title":"My terminal","payment_method":"cc","processor":"zgate","mcc":"111' .
                '1","tax_surcharge_config":2,"partner":"standalone","location_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt_clerk_number":true,"vt_bill' .
                'ing_phone":true,"vt_enable_tip":true,"ach_allow_debit":true,"ach_allow_credit":' .
                'true,"ach_allow_refund":true,"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_o' .
                'rder_num":true,"vt_enable":true,"receipt_show_contact_name":true,"display_avs":' .
                'true,"card_type_visa":true,"card_type_mc":true,"card_type_disc":true,"card_type' .
                '_amex":true,"card_type_diners":true,"card_type_jcb":true,"card_type_ebt":true,"' .
                'allow_ebt_cash_benefit":true,"allow_ebt_food_stamp":true,"invoice_location":tru' .
                'e,"allow_partial_authorization":true,"allow_recurring_partial_authorization":tr' .
                'ue,"auto_decline_cvv":true,"auto_decline_street":true,"auto_decline_zip":true,"' .
                'split_payments_allow":true,"vt_show_custom_fields":true,"receipt_show_custom_fi' .
                'elds":true,"vt_override_sales_tax_allowed":true,"vt_enable_sales_tax":true,"vt_' .
                'require_zip":true,"vt_require_street":true,"auto_decline_cavv":true,"current_ba' .
                'tch":34,"dup_check_per_batch":null,"paylink_allow":false,"quick_invoice_allow":' .
                'false,"level3_allow":false,"payfac_enable":false,"enable_3ds":false,"sales_offi' .
                'ce_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,"surcharge_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce":false,"level3_default":{"de' .
                'stination_country_code":"840","duty_amount":0,"freight_amount":0,"national_tax"' .
                ':2,"sales_tax":200,"shipfrom_zip_code":"AZ12345","shipto_zip_code":"MI48335","t' .
                'ax_amount":0,"tax_exempt":"0","customer_vat_registration":"12345678","merchant_' .
                'vat_registration":"123456","order_date":"171006","summary_commodity_code":"C1K2' .
                '","tax_rate":0,"unique_vat_ref_number":"vat1234","line_items":[{"alternate_tax_' .
                'id":"1234","debit_credit":"C","description":"cool drink","discount_amount":10,"' .
                'discount_rate":11,"product_code":"coke12345678","quantity":5,"tax_amount":3,"ta' .
                'x_rate":0,"tax_type_applied":"22","tax_type_id":"a1","unit_code":"gll","unit_co' .
                'st":10,"commodity_code":"cc123456","other_tax_amount":0}]},"cau_subscribe_type_' .
                'id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","product_billing' .
                '_group_id":"nofees","account_number":"12345678","run_avs_on_accountvault_create' .
                '":false,"accountvault_expire_notification_email_enable":false,"debit_allow_void' .
                '":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_show_currency"' .
                ':true,"receipt_show_currency":false,"allow_blind_refund":false,"vt_show_company' .
                '_name":false,"receipt_show_company_name":false,"bank_funded_only":false,"requir' .
                'e_cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_cnp":true,"show_secondary_am' .
                'ount":false,"allow_secondary_amount":false,"show_google_pay":true,"show_apple_p' .
                'ay":true,"batch_risk_config":{},"currency_code":840,"enable_ach_validation":fal' .
                'se,"enable_ach_retry":false,"id":"11e95f8ec39de8fbdb0a4f1a","active":true,"crea' .
                'ted_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_ap' .
                'i_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_allowed":false,"fortis_id' .
                '":"8149742","product_billing_group_code":"nofees","cau_subscribe_type_code":0}]' .
                ',"product_file":{"title":"My terminal","product_file_credential_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modifi' .
                'ed_ts":1422040992,"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"' .
                'product_accountvault":{"title":"My terminal","location_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"m' .
                'odified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_u' .
                'ser_id":"11e95f8ec39de8fbdb0a4f1a"},"product_token":{"title":"My terminal","loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","active":t' .
                'rue,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"product_recu' .
                'rring":{"title":"Fortispay RbYN6y","location_id":"11e95f8ec39de8fbdb0a4f1a","lo' .
                'cation_api_id":"11e95f8ec39de8fbdb0a4f1a","send_declined_notifications":true,"r' .
                'equire_full_payment":true,"expire_notification_email_enable":true,"expire_notif' .
                'ication_sms_enable":true,"notification_days_default":1,"id":"11e95f8ec39de8fbdb' .
                '0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"tags":[{' .
                '"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"terminals":' .
                '[{"location_id":"11e95f8ec39de8fbdb0a4f1a","default_product_transaction_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","terminal_application_id":"11e95f8ec39de8fbdb0a4f1a","t' .
                'erminal_cvm_id":"11e95f8ec39de8fbdb0a4f1a","terminal_manufacturer_code":"1","ti' .
                'tle":"My terminal","mac_address":"3D:F2:C9:A6:B3:4F","local_ip_address":"192.16' .
                '8.0.10","port":10009,"serial_number":"1234567890","terminal_number":"9734567890' .
                '12367","terminal_timeouts":{"card_entry_timeout":47,"device_terms_prompt_timeou' .
                't":30,"overall_timeout":125,"pin_entry_timeout":40,"signature_input_timeout":35' .
                ',"signature_submit_timeout":38,"status_display_time":12,"tip_cashback_timeout":' .
                '25,"transaction_timeout":17},"tip_percents":{"percent_1":0,"percent_2":2,"perce' .
                'nt_3":99},"header_line_1":"line 1 sample","header_line_2":"line 2 sample","head' .
                'er_line_3":"line 3 sample","header_line_4":"line 4 sample","header_line_5":"lin' .
                'e 5 sample","trailer_line_1":"trailer 1 sample","trailer_line_2":"trailer 2 sam' .
                'ple","trailer_line_3":"trailer 3 sample","trailer_line_4":"trailer 4 sample","t' .
                'railer_line_5":"trailer 5 sample","default_checkin":"2021-12-01","default_check' .
                'out":"2021-12-01","default_room_rate":56,"default_room_number":"303","debit":fa' .
                'lse,"emv":false,"cashback_enable":false,"print_enable":false,"sig_capture_enabl' .
                'e":false,"is_provisioned":false,"tip_enable":false,"validated_decryption":false' .
                ',"communication_type":"http","active":true,"id":"11e95f8ec39de8fbdb0a4f1a","cre' .
                'ated_ts":1422040992,"modified_ts":1422040992,"last_registration_ts":1422040992,' .
                '"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8' .
                'fbdb0a4f1a"}]}],"links":{"type":"Links","first":"/v1/endpoint?page[size]=10&pag' .
                'e[number]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","next":"/v1' .
                '/endpoint?page[size]=10&page[number]=7","last":"/v1/endpoint?page[size]=10&page' .
                '[number]=42"},"pagination":{"type":"Pagination","total_count":423,"page_count":' .
                '42,"page_number":6,"page_size":10},"sort":{"type":"Sorting","fields":[{"field":' .
                '"last_name","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testViewSingleLocationRecord()
    {
        // Parameters for the API call
        $locationId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleLocationRecord($locationId, $expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Location","data":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204' .
                '0992,"modified_ts":1422040992,"account_number":"5454545454545454","address":{"c' .
                'ity":"Novi","state":"MI","postal_code":"48375","country":"US"},"branding_domain' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"defau' .
                'lt_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","ema' .
                'il_reply_to":"email@domain.com","fax":"3339998822","location_api_id":"location-' .
                '111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1",' .
                '"location_c2":"custom 2","location_c3":"custom data 3","name":"Sample Company H' .
                'eadquarters","office_phone":"2481234567","office_ext_phone":"1021021209","tz":"' .
                'America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":t' .
                'rue,"show_contact_files":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","loc' .
                'ation_type":"merchant","ticket_hash_key":"A5F443CADF4AE34BBCAADF4","parent":{"i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,' .
                '"account_number":"5454545454545454","address":{"city":"Novi","state":"MI","post' .
                'al_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242' .
                'bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domain.com' .
                '","fax":"3339998822","location_api_id":"location-111111","location_api_key":"AE' .
                '34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","loca' .
                'tion_c3":"custom data 3","name":"Sample Company Headquarters","office_phone":"2' .
                '481234567","office_ext_phone":"1021021209","tz":"America/New_York","parent_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":true,' .
                '"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","ticket' .
                '_hash_key":"A5F443CADF4AE34BBCAADF4"},"users":[{"account_number":"5454545454545' .
                '454","branding_domain_url":"{branding_domain_url}","cell_phone":"3339998822","c' .
                'ompany_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email"' .
                ':"email@domain.com","email_trx_receipt":true,"home_phone":"3339998822","first_n' .
                'ame":"John","last_name":"Smith","locale":"en-US","office_phone":"3339998822","o' .
                'ffice_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires' .
                '_new_password":null,"terms_condition_code":"20220308","tz":"America/New_York","' .
                'ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv","p' .
                'rocess_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"' .
                '},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key' .
                '":null,"user_type_code":100,"password":null,"zip":"48375","location_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false,"add' .
                'ress":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":14220' .
                '40992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0' .
                '.10","current_date_time":"2019-03-11T10:38:26-0700","current_login":1422040992,' .
                '"log_api_response_body_ts":1422040992}],"is_deletable":true,"terminals":[{"loca' .
                'tion_id":"11e95f8ec39de8fbdb0a4f1a","default_product_transaction_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","terminal_application_id":"11e95f8ec39de8fbdb0a4f1a","terminal' .
                '_cvm_id":"11e95f8ec39de8fbdb0a4f1a","terminal_manufacturer_code":"1","title":"M' .
                'y terminal","mac_address":"3D:F2:C9:A6:B3:4F","local_ip_address":"192.168.0.10"' .
                ',"port":10009,"serial_number":"1234567890","terminal_number":"973456789012367",' .
                '"terminal_timeouts":{"card_entry_timeout":47,"device_terms_prompt_timeout":30,"' .
                'overall_timeout":125,"pin_entry_timeout":40,"signature_input_timeout":35,"signa' .
                'ture_submit_timeout":38,"status_display_time":12,"tip_cashback_timeout":25,"tra' .
                'nsaction_timeout":17},"tip_percents":{"percent_1":0,"percent_2":2,"percent_3":9' .
                '9},"header_line_1":"line 1 sample","header_line_2":"line 2 sample","header_line' .
                '_3":"line 3 sample","header_line_4":"line 4 sample","header_line_5":"line 5 sam' .
                'ple","trailer_line_1":"trailer 1 sample","trailer_line_2":"trailer 2 sample","t' .
                'railer_line_3":"trailer 3 sample","trailer_line_4":"trailer 4 sample","trailer_' .
                'line_5":"trailer 5 sample","default_checkin":"2021-12-01","default_checkout":"2' .
                '021-12-01","default_room_rate":56,"default_room_number":"303","debit":false,"em' .
                'v":false,"cashback_enable":false,"print_enable":false,"sig_capture_enable":fals' .
                'e,"is_provisioned":false,"tip_enable":false,"validated_decryption":false,"commu' .
                'nication_type":"http","active":true,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts' .
                '":1422040992,"modified_ts":1422040992,"last_registration_ts":1422040992,"create' .
                'd_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4' .
                'f1a"}],"branding_domain":{"url":"fortispayrbyn9y.sandbox.zeamster.com","title":' .
                '"Test Brand Domain Title 2","logo":"","support_email":"email@domain.com","allow' .
                '_contact_signup":true,"allow_contact_registration":true,"allow_contact_login":t' .
                'rue,"registration_fields":["account_number"],"company_name":null,"nav_color":nu' .
                'll,"button_primary_color":null,"logo_background_color":null,"icon_background_co' .
                'lor":null,"menu_text_background_color":null,"menu_text_color":null,"right_menu_' .
                'background_color":null,"right_menu_text_color":null,"button_primary_text_color"' .
                ':null,"nav_logo":null,"fav_icon":null,"aes_key":null,"help_text":null,"email_re' .
                'ply_to":"email@domain.com","email":"email@domain.com","custom_javascript":null,' .
                '"custom_theme":null,"custom_css":null,"contact_user_default_entry_page":"dashbo' .
                'ard","contact_user_default_auth_roles":[null],"custom_stylesheet_url":"https://' .
                '127.0.0.1/receiver","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"mo' .
                'dified_ts":1422040992},"product_invoice":{"title":"Sample title","quote_number_' .
                'start":1,"quote_number_increment":1,"quote_number_current":1,"invoice_number_st' .
                'art":1,"invoice_number_increment":1,"invoice_number_current":1,"tax_rate":0,"ta' .
                'x_fee":0,"monthly_fee":0,"per_invoice_fee":0,"per_quote_fee":0,"require_pay_in_' .
                'full":true,"selectable":1,"reportable":1,"portfolio_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","location_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'reated_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"product_files":[{"' .
                'title":"My terminal","product_file_credential_id":"11e95f8ec39de8fbdb0a4f1a","i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,' .
                '"active":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"created_user":{"a' .
                'ccount_number":"5454545454545454","branding_domain_url":"{branding_domain_url}"' .
                ',"cell_phone":"3339998822","company_name":"Fortis Payment Systems, LLC","contac' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home' .
                '_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"en-US","' .
                'office_phone":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condition_code":"202203' .
                '08","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,' .
                '"report_export_type":"csv","process_method":"virtual_terminal","default_termina' .
                'l":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8' .
                'dfn8238f923w2","user_hash_key":null,"user_type_code":100,"password":null,"zip":' .
                '"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":fal' .
                'se,"is_invitation":false,"address":{"city":"Novi","state":"MI","postal_code":"4' .
                '8375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_atte' .
                'mpts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_ts":142204' .
                '0992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":142204099' .
                '2,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700' .
                '","current_login":1422040992,"log_api_response_body_ts":1422040992},"changelogs' .
                '":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","' .
                'model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"164' .
                '3616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com' .
                '","first_name":"Bob","last_name":"Fairview"}}],"product_transactions":[{"proces' .
                'sor_version":"1_0_0","title":"My terminal","payment_method":"cc","processor":"z' .
                'gate","mcc":"1111","tax_surcharge_config":2,"partner":"standalone","location_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt_clerk_numbe' .
                'r":true,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allow_debit":true,"ac' .
                'h_allow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt_street":true,"vt' .
                '_zip":true,"vt_order_num":true,"vt_enable":true,"receipt_show_contact_name":tru' .
                'e,"display_avs":true,"card_type_visa":true,"card_type_mc":true,"card_type_disc"' .
                ':true,"card_type_amex":true,"card_type_diners":true,"card_type_jcb":true,"card_' .
                'type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_stamp":true,"invoi' .
                'ce_location":true,"allow_partial_authorization":true,"allow_recurring_partial_a' .
                'uthorization":true,"auto_decline_cvv":true,"auto_decline_street":true,"auto_dec' .
                'line_zip":true,"split_payments_allow":true,"vt_show_custom_fields":true,"receip' .
                't_show_custom_fields":true,"vt_override_sales_tax_allowed":true,"vt_enable_sale' .
                's_tax":true,"vt_require_zip":true,"vt_require_street":true,"auto_decline_cavv":' .
                'true,"current_batch":34,"dup_check_per_batch":null,"paylink_allow":false,"quick' .
                '_invoice_allow":false,"level3_allow":false,"payfac_enable":false,"enable_3ds":f' .
                'alse,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":f' .
                'alse,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce":false,"leve' .
                'l3_default":{"destination_country_code":"840","duty_amount":0,"freight_amount":' .
                '0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ12345","shipto_zip_co' .
                'de":"MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_registration":"1234' .
                '5678","merchant_vat_registration":"123456","order_date":"171006","summary_commo' .
                'dity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","line_items":[' .
                '{"alternate_tax_id":"1234","debit_credit":"C","description":"cool drink","disco' .
                'unt_amount":10,"discount_rate":11,"product_code":"coke12345678","quantity":5,"t' .
                'ax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id":"a1","unit_code' .
                '":"gll","unit_cost":10,"commodity_code":"cc123456","other_tax_amount":0}]},"cau' .
                '_subscribe_type_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2",' .
                '"product_billing_group_id":"nofees","account_number":"12345678","run_avs_on_acc' .
                'ountvault_create":false,"accountvault_expire_notification_email_enable":false,"' .
                'debit_allow_void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"v' .
                't_show_currency":true,"receipt_show_currency":false,"allow_blind_refund":false,' .
                '"vt_show_company_name":false,"receipt_show_company_name":false,"bank_funded_onl' .
                'y":false,"require_cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_cnp":true,"s' .
                'how_secondary_amount":false,"allow_secondary_amount":false,"show_google_pay":tr' .
                'ue,"show_apple_pay":true,"batch_risk_config":{},"currency_code":840,"enable_ach' .
                '_validation":false,"enable_ach_retry":false,"id":"11e95f8ec39de8fbdb0a4f1a","ac' .
                'tive":true,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","produc' .
                't_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_allowed":' .
                'false,"fortis_id":"8149742","product_billing_group_code":"nofees","cau_subscrib' .
                'e_type_code":0}],"terminal_routers":[{"mac_address":"3D:F2:C9:A6:B3:4F","locati' .
                'on_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":' .
                '1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a' .
                '"}],"developer_company":{"title":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"active":true,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"de' .
                'veloper_company_id":"sample developer company id","helppages":[{"user_type_code' .
                '":100,"body":"Sample Body","title":"Sample Title","id":"11e95f8ec39de8fbdb0a4f1' .
                'a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"quick_invoic' .
                'e_setting":{"location_api_id":"11e95f8ec39de8fbdb0a4f1a","location_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","quick_invoice_template":"<html>Template<html>","default_all' .
                'ow_partial_pay":true,"default_notification_on_due_date":true,"default_notificat' .
                'ion_days_after_due_date":7,"default_notification_days_before_due_date":3,"show_' .
                'custom_fields":false,"id":"11e95f8ec39de8fbdb0a4f1a"},"location_billing_account' .
                's":[{"title":"Billing Acccount Title","location_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"ach_sec_code":null,"account_number":null,"routing":null,"exp_date":"0722","bil' .
                'ling_zip":"48375","account_type":null,"account_holder_name":"John Smith","id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"cre' .
                'ated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","billing_descriptor":null,"payment_method":null,"portfolio_id":"11e95f8' .
                'ec39de8fbdb0a4f1a"}],"marketplaces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"marketplace_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"locationmarketplaces":[{"loca' .
                'tion_id":"11e95f8ec39de8fbdb0a4f1a","marketplace_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"location_api_id":null,"user_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a"}],"addons":[{"title":" ","secret":" ","iframe_url":" ","location_setup_url"' .
                ':" ","user_setup_url":" ","encrypt_url_params":true}]}}'
            )))
            ->assert();
    }
}
