<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\QuickInvoicesController;
use FortisAPILib\Exceptions;

class QuickInvoicesControllerTest extends BaseTestController
{
    /**
     * @var QuickInvoicesController QuickInvoicesController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getQuickInvoicesController();
    }

    public function testListAllQuickInvoicesRelated()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllQuickInvoicesRelated(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"QuickInvoicesCollection","list":[{"location_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","title":"My terminal","cc_product_transaction_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","ach_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","due_date":"2021-12' .
                '-01","item_list":[{"name":"Bread","amount":2015}],"allow_overpayment":true,"ban' .
                'k_funded_only_override":true,"email":"email@domain.com","contact_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","contact_api_id":"contact12345","quick_invoice_api_id":"quicki' .
                'nvoice12345","customer_id":"11e95f8ec39de8fbdb0a4f1a","expire_date":"2021-12-01' .
                '","allow_partial_pay":true,"attach_files_to_email":true,"send_email":true,"invo' .
                'ice_number":"invoice12345","item_header":"Quick invoice header sample","item_fo' .
                'oter":"Thank you","amount_due":245.36,"notification_email":"email@domain.com","' .
                'status_id":1,"status_code":1,"note":"some note","notification_days_before_due_d' .
                'ate":3,"notification_days_after_due_date":7,"notification_on_due_date":true,"se' .
                'nd_text_to_pay":true,"files":[{"file":{},"resource_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","resource":"Contact","product_file_id":"11e95f8ec39de8fbdb0a4f1a","file_cate' .
                'gory_id":"11e95f8ec39de8fbdb0a4f1a","visibility_group_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"remaining_balance":245.' .
                '36,"single_payment_min_amount":500,"single_payment_max_amount":500000,"cell_pho' .
                'ne":"3339998822","tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My ' .
                'terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts"' .
                ':1422040992}],"quick_invoice_c1":"custom-data-1","quick_invoice_c2":"custom-dat' .
                'a-2","quick_invoice_c3":"custom-data-3","auto_reopen":true,"id":"11e95f8ec39de8' .
                'fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"created_user_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","activ' .
                'e":true,"payment_status_id":1,"is_active":true,"quick_invoice_setting":{"locati' .
                'on_api_id":"11e95f8ec39de8fbdb0a4f1a","location_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"quick_invoice_template":"<html>Template<html>","default_allow_partial_pay":tru' .
                'e,"default_notification_on_due_date":true,"default_notification_days_after_due_' .
                'date":7,"default_notification_days_before_due_date":3,"show_custom_fields":fals' .
                'e,"id":"11e95f8ec39de8fbdb0a4f1a"},"quick_invoice_views":[{"id":"11e95f8ec39de8' .
                'fbdb0a4f1a","quick_invoice_id":"Quick Invoice ID","created_ts":1422040992}],"lo' .
                'cation":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":' .
                '1422040992,"account_number":"5454545454545454","address":{"city":"Novi","state"' .
                ':"MI","postal_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d5' .
                '15f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email' .
                '@domain.com","fax":"3339998822","location_api_id":"location-111111","location_a' .
                'pi_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"cust' .
                'om 2","location_c3":"custom data 3","name":"Sample Company Headquarters","offic' .
                'e_phone":"2481234567","office_ext_phone":"1021021209","tz":"America/New_York","' .
                'parent_id":"11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_f' .
                'iles":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"mercha' .
                'nt","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"created_user":{"account_numbe' .
                'r":"5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone' .
                '":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fb' .
                'db0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"333' .
                '9998822","first_name":"John","last_name":"Smith","locale":"en-US","office_phone' .
                '":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"Am' .
                'erica/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_expo' .
                'rt_type":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8e' .
                'c39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w' .
                '2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","loc' .
                'ation_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invit' .
                'ation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","count' .
                'ry":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"las' .
                't_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"create' .
                'd_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agr' .
                'ee_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_l' .
                'ogin":1422040992,"log_api_response_body_ts":1422040992},"modified_user":{"accou' .
                'nt_number":"5454545454545454","branding_domain_url":"{branding_domain_url}","ce' .
                'll_phone":"3339998822","company_name":"Fortis Payment Systems, LLC","contact_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_pho' .
                'ne":"3339998822","first_name":"John","last_name":"Smith","locale":"en-US","offi' .
                'ce_phone":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","requires_new_password":null,"terms_condition_code":"20220308",' .
                '"tz":"America/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"rep' .
                'ort_export_type":"csv","process_method":"virtual_terminal","default_terminal":"' .
                '11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8' .
                '238f923w2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"483' .
                '75","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"' .
                'is_invitation":false,"address":{"city":"Novi","state":"MI","postal_code":"48375' .
                '","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts' .
                '":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992' .
                ',"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"t' .
                'erms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","c' .
                'urrent_login":1422040992,"log_api_response_body_ts":1422040992},"changelogs":[{' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","mode' .
                'l":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","chan' .
                'gelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616' .
                '000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","f' .
                'irst_name":"Bob","last_name":"Fairview"}}],"contact":{"location_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","first_na' .
                'me":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.36,"addr' .
                'ess":{"city":"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"' .
                'company_name":"Fortis Payment Systems, LLC","header_message":"This is a sample ' .
                'message for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_ph' .
                'one":"3339998822","office_phone":"3339998822","office_phone_ext":"5","home_phon' .
                'e_country_code":"+1","office_phone_country_code":"+1","cell_phone_country_code"' .
                ':"+1","header_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_' .
                'c2":"anything","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"email":"email@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"acti' .
                've":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"log_emails":[{"subject"' .
                ':"Payment Receipt - 12skiestech","body":"This email is being sent from a server' .
                '.","source_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return' .
                '_path":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"01000' .
                '17e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction","re' .
                'ason_model_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@ze' .
                'amster.com>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"log_sms' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","body":" ","reason_model":" ","reason_model_' .
                'id":" ","provider_id":" ","status":" ","sender":" ","recipient":" ","created_ts' .
                '":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"transactions":[{"ad' .
                'ditional_amounts":[{"type":"cashback","amount":10,"account_type":"credit","curr' .
                'ency":840}],"billing_address":{"city":"Novi","state":"Michigan","postal_code":"' .
                '48375","phone":"3339998822","country":"USA"},"checkin_date":"2021-12-01","check' .
                'out_date":"2021-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","custom_data":{},"customer_id":"customerid","description":"some descrip' .
                'tion","identity_verification":{"dl_state":"MI","dl_number":"1235567","dob_year"' .
                ':"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY2' .
                '9kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","instal' .
                'lment":true,"installment_number":1,"installment_count":1,"location_api_id":"loc' .
                'ation-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_trans' .
                'action_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"' .
                'notification_email_address":"johnsmith@smiths.com","order_number":"433659378839' .
                '","po_number":"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","rec' .
                'urring":false,"recurring_number":1,"room_num":"303","room_rate":95,"save_accoun' .
                't":false,"save_account_title":"John Account","subtotal_amount":599,"surcharge_a' .
                'mount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transaction_amou' .
                'nt":0,"secondary_amount":0,"transaction_api_id":"transaction-payment-abcd123","' .
                'transaction_c1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c' .
                '3":"custom-data-3","bank_funded_only_override":false,"allow_partial_authorizati' .
                'on_override":false,"auto_decline_cvv_override":false,"auto_decline_street_overr' .
                'ide":false,"auto_decline_zip_override":false,"ebt_type":"food_stamp","id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"termina' .
                'l_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"smith","account_type":"' .
                'checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_c' .
                'ode":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enhanced":"N",' .
                '"cardholder_present":true,"card_present":true,"check_number":"8520748520963","c' .
                'ustomer_ip":"192.168.0.10","cvv_response":"N","entry_mode_id":"C","emv_receipt_' .
                'data":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN":"US Maestro","CVM":"' .
                'Pin Verified","TSI":"e800","TVR":"0800008000"},"first_six":"545454","last_four"' .
                ':"5454","payment_method":"cc","terminal_serial_number":"1234567890","transactio' .
                'n_settlement_status":null,"charge_back_date":"2021-12-01","is_recurring":true,"' .
                'notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_cod' .
                'e_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01"' .
                ',"status_code":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage"' .
                ':"APPROVED","voucher_number":"1234","void_date":"2021-12-01","batch":"2","terms' .
                '_agree":true,"response_message":null,"return_date":"2021-12-01","trx_source_id"' .
                ':8,"routing_number":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","' .
                'is_token":true,"installment_total":1,"installment_counter":1,"account_vault_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"' .
                '}],"cc_product_transaction":{"processor_version":"1_0_0","title":"My terminal",' .
                '"payment_method":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config":2' .
                ',"partner":"standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{}' .
                ',"processor_data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_' .
                'tip":true,"ach_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":tru' .
                'e,"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":' .
                'true,"receipt_show_contact_name":true,"display_avs":true,"card_type_visa":true,' .
                '"card_type_mc":true,"card_type_disc":true,"card_type_amex":true,"card_type_dine' .
                'rs":true,"card_type_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":tru' .
                'e,"allow_ebt_food_stamp":true,"invoice_location":true,"allow_partial_authorizat' .
                'ion":true,"allow_recurring_partial_authorization":true,"auto_decline_cvv":true,' .
                '"auto_decline_street":true,"auto_decline_zip":true,"split_payments_allow":true,' .
                '"vt_show_custom_fields":true,"receipt_show_custom_fields":true,"vt_override_sal' .
                'es_tax_allowed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_requi' .
                're_street":true,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_batc' .
                'h":null,"paylink_allow":false,"quick_invoice_allow":false,"level3_allow":false,' .
                '"payfac_enable":false,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","hosted_payment_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","allow_big_commerce":false,"level3_default":{"destination_country_code":"84' .
                '0","duty_amount":0,"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfro' .
                'm_zip_code":"AZ12345","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"' .
                '0","customer_vat_registration":"12345678","merchant_vat_registration":"123456",' .
                '"order_date":"171006","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_' .
                'ref_number":"vat1234","line_items":[{"alternate_tax_id":"1234","debit_credit":"' .
                'C","description":"cool drink","discount_amount":10,"discount_rate":11,"product_' .
                'code":"coke12345678","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied' .
                '":"22","tax_type_id":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"cc' .
                '123456","other_tax_amount":0}]},"cau_subscribe_type_id":0,"location_billing_acc' .
                'ount_id":"11eb88b873980c64a21e5fd2","product_billing_group_id":"nofees","accoun' .
                't_number":"12345678","run_avs_on_accountvault_create":false,"accountvault_expir' .
                'e_notification_email_enable":false,"debit_allow_void":false,"quick_invoice_text' .
                '_to_pay":false,"sms_enable":false,"vt_show_currency":true,"receipt_show_currenc' .
                'y":false,"allow_blind_refund":false,"vt_show_company_name":false,"receipt_show_' .
                'company_name":false,"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,"r' .
                'equire_cvv_on_tokenized_cnp":true,"show_secondary_amount":false,"allow_secondar' .
                'y_amount":false,"show_google_pay":true,"show_apple_pay":true,"batch_risk_config' .
                '":{},"currency_code":840,"enable_ach_validation":false,"enable_ach_retry":false' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modifie' .
                'd_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","is_secondary_amount_allowed":false,"fortis_id":"8149742","product_billin' .
                'g_group_code":"nofees","cau_subscribe_type_code":0},"ach_product_transaction":{' .
                '"processor_version":"1_0_0","title":"My terminal","payment_method":"cc","proces' .
                'sor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"standalone","loca' .
                'tion_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt_cler' .
                'k_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allow_debit":t' .
                'rue,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt_street":t' .
                'rue,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receipt_show_contact_na' .
                'me":true,"display_avs":true,"card_type_visa":true,"card_type_mc":true,"card_typ' .
                'e_disc":true,"card_type_amex":true,"card_type_diners":true,"card_type_jcb":true' .
                ',"card_type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_stamp":true' .
                ',"invoice_location":true,"allow_partial_authorization":true,"allow_recurring_pa' .
                'rtial_authorization":true,"auto_decline_cvv":true,"auto_decline_street":true,"a' .
                'uto_decline_zip":true,"split_payments_allow":true,"vt_show_custom_fields":true,' .
                '"receipt_show_custom_fields":true,"vt_override_sales_tax_allowed":true,"vt_enab' .
                'le_sales_tax":true,"vt_require_zip":true,"vt_require_street":true,"auto_decline' .
                '_cavv":true,"current_batch":34,"dup_check_per_batch":null,"paylink_allow":false' .
                ',"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":false,"enable' .
                '_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_a' .
                'llow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce":fals' .
                'e,"level3_default":{"destination_country_code":"840","duty_amount":0,"freight_a' .
                'mount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ12345","shipto' .
                '_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_registration' .
                '":"12345678","merchant_vat_registration":"123456","order_date":"171006","summar' .
                'y_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","line_i' .
                'tems":[{"alternate_tax_id":"1234","debit_credit":"C","description":"cool drink"' .
                ',"discount_amount":10,"discount_rate":11,"product_code":"coke12345678","quantit' .
                'y":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id":"a1","un' .
                'it_code":"gll","unit_cost":10,"commodity_code":"cc123456","other_tax_amount":0}' .
                ']},"cau_subscribe_type_id":0,"location_billing_account_id":"11eb88b873980c64a21' .
                'e5fd2","product_billing_group_id":"nofees","account_number":"12345678","run_avs' .
                '_on_accountvault_create":false,"accountvault_expire_notification_email_enable":' .
                'false,"debit_allow_void":false,"quick_invoice_text_to_pay":false,"sms_enable":f' .
                'alse,"vt_show_currency":true,"receipt_show_currency":false,"allow_blind_refund"' .
                ':false,"vt_show_company_name":false,"receipt_show_company_name":false,"bank_fun' .
                'ded_only":false,"require_cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_cnp":' .
                'true,"show_secondary_amount":false,"allow_secondary_amount":false,"show_google_' .
                'pay":true,"show_apple_pay":true,"batch_risk_config":{},"currency_code":840,"ena' .
                'ble_ach_validation":false,"enable_ach_retry":false,"id":"11e95f8ec39de8fbdb0a4f' .
                '1a","active":true,"created_ts":1422040992,"modified_ts":1422040992,"created_use' .
                'r_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_al' .
                'lowed":false,"fortis_id":"8149742","product_billing_group_code":"nofees","cau_s' .
                'ubscribe_type_code":0},"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBl' .
                'acklisted":true,"detail":true,"created_ts":1422040992},"sms_blacklist":{"id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":142204' .
                '0992}}],"links":{"type":"Links","first":"/v1/endpoint?page[size]=10&page[number' .
                ']=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","next":"/v1/endpoin' .
                't?page[size]=10&page[number]=7","last":"/v1/endpoint?page[size]=10&page[number]' .
                '=42"},"pagination":{"type":"Pagination","total_count":423,"page_count":42,"page' .
                '_number":6,"page_size":10},"sort":{"type":"Sorting","fields":[{"field":"last_na' .
                'me","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testDeleteQuickInvoice()
    {
        // Parameters for the API call
        $quickInvoiceId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deleteQuickInvoice($quickInvoiceId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"QuickInvoice","data":{"location_id":"11e95f8ec39de8fbdb0a4f1a","title' .
                '":"My terminal","cc_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","ach_pro' .
                'duct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","due_date":"2021-12-01","item_l' .
                'ist":[{"name":"Bread","amount":2015}],"allow_overpayment":true,"bank_funded_onl' .
                'y_override":true,"email":"email@domain.com","contact_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","contact_api_id":"contact12345","quick_invoice_api_id":"quickinvoice12345"' .
                ',"customer_id":"11e95f8ec39de8fbdb0a4f1a","expire_date":"2021-12-01","allow_par' .
                'tial_pay":true,"attach_files_to_email":true,"send_email":true,"invoice_number":' .
                '"invoice12345","item_header":"Quick invoice header sample","item_footer":"Thank' .
                ' you","amount_due":245.36,"notification_email":"email@domain.com","status_id":1' .
                ',"status_code":1,"note":"some note","notification_days_before_due_date":3,"noti' .
                'fication_days_after_due_date":7,"notification_on_due_date":true,"send_text_to_p' .
                'ay":true,"files":[{"file":{},"resource_id":"11e95f8ec39de8fbdb0a4f1a","resource' .
                '":"Contact","product_file_id":"11e95f8ec39de8fbdb0a4f1a","file_category_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","visibility_group_id":"11e95f8ec39de8fbdb0a4f1a","id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"cre' .
                'ated_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"remaining_balance":245.36,"single_p' .
                'ayment_min_amount":500,"single_payment_max_amount":500000,"cell_phone":"3339998' .
                '822","tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}' .
                '],"quick_invoice_c1":"custom-data-1","quick_invoice_c2":"custom-data-2","quick_' .
                'invoice_c3":"custom-data-3","auto_reopen":true,"id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","active":true,"pay' .
                'ment_status_id":1,"is_active":true,"quick_invoice_setting":{"location_api_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","location_id":"11e95f8ec39de8fbdb0a4f1a","quick_invoi' .
                'ce_template":"<html>Template<html>","default_allow_partial_pay":true,"default_n' .
                'otification_on_due_date":true,"default_notification_days_after_due_date":7,"def' .
                'ault_notification_days_before_due_date":3,"show_custom_fields":false,"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a"},"quick_invoice_views":[{"id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"quick_invoice_id":"Quick Invoice ID","created_ts":1422040992}],"location":{"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'account_number":"5454545454545454","address":{"city":"Novi","state":"MI","posta' .
                'l_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242b' .
                'b2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domain.com"' .
                ',"fax":"3339998822","location_api_id":"location-111111","location_api_key":"AE3' .
                '4BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","locat' .
                'ion_c3":"custom data 3","name":"Sample Company Headquarters","office_phone":"24' .
                '81234567","office_ext_phone":"1021021209","tz":"America/New_York","parent_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":true,"' .
                'created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","ticket_' .
                'hash_key":"A5F443CADF4AE34BBCAADF4"},"created_user":{"account_number":"54545454' .
                '54545454","branding_domain_url":"{branding_domain_url}","cell_phone":"333999882' .
                '2","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","e' .
                'mail":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998822","fi' .
                'rst_name":"John","last_name":"Smith","locale":"en-US","office_phone":"333999882' .
                '2","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","req' .
                'uires_new_password":null,"terms_condition_code":"20220308","tz":"America/New_Yo' .
                'rk","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type":"cs' .
                'v","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a' .
                '4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_has' .
                'h_key":null,"user_type_code":100,"password":null,"zip":"48375","location_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false' .
                ',"address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":' .
                '1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.' .
                '168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login":142204' .
                '0992,"log_api_response_body_ts":1422040992},"modified_user":{"account_number":"' .
                '5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone":"3' .
                '339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998' .
                '822","first_name":"John","last_name":"Smith","locale":"en-US","office_phone":"3' .
                '339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"Americ' .
                'a/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_t' .
                'ype":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39d' .
                'e8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","' .
                'user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","locatio' .
                'n_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitatio' .
                'n":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","country":' .
                '"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_lo' .
                'gin_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_i' .
                'p":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login' .
                '":1422040992,"log_api_response_body_ts":1422040992},"changelogs":[{"id":"11e95f' .
                '8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"Transact' .
                'ionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"' .
                'Bob","last_name":"Fairview"}}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_number":"54545433332","contact_api_id":"137","first_name":"John","' .
                'last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city"' .
                ':"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"company_name' .
                '":"Fortis Payment Systems, LLC","header_message":"This is a sample message for ' .
                'you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999' .
                '8822","office_phone":"3339998822","office_phone_ext":"5","home_phone_country_co' .
                'de":"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","heade' .
                'r_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anythin' .
                'g","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"ema' .
                'il@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"cr' .
                'eated_user_id":"11e95f8ec39de8fbdb0a4f1a"},"log_emails":[{"subject":"Payment Re' .
                'ceipt - 12skiestech","body":"This email is being sent from a server.","source_a' .
                'ddress":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"1' .
                '2skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-' .
                'e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_model_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>"' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"log_sms":{"id":"11e' .
                '95f8ec39de8fbdb0a4f1a","body":" ","reason_model":" ","reason_model_id":" ","pro' .
                'vider_id":" ","status":" ","sender":" ","recipient":" ","created_ts":1422040992' .
                ',"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"transactions":[{"additional_amo' .
                'unts":[{"type":"cashback","amount":10,"account_type":"credit","currency":840}],' .
                '"billing_address":{"city":"Novi","state":"Michigan","postal_code":"48375","phon' .
                'e":"3339998822","country":"USA"},"checkin_date":"2021-12-01","checkout_date":"2' .
                '021-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec39de8fbdb0a4f1a","cus' .
                'tom_data":{},"customer_id":"customerid","description":"some description","ident' .
                'ity_verification":{"dl_state":"MI","dl_number":"1235567","dob_year":"1980"},"ii' .
                'as_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","ima' .
                'ge_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","installment":true,' .
                '"installment_number":1,"installment_count":1,"location_api_id":"location-api-id' .
                '-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"notification' .
                '_email_address":"johnsmith@smiths.com","order_number":"433659378839","po_number' .
                '":"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recurring":fals' .
                'e,"recurring_number":1,"room_num":"303","room_rate":95,"save_account":false,"sa' .
                've_account_title":"John Account","subtotal_amount":599,"surcharge_amount":100,"' .
                'tags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transaction_amount":0,"secon' .
                'dary_amount":0,"transaction_api_id":"transaction-payment-abcd123","transaction_' .
                'c1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c3":"custom-d' .
                'ata-3","bank_funded_only_override":false,"allow_partial_authorization_override"' .
                ':false,"auto_decline_cvv_override":false,"auto_decline_street_override":false,"' .
                'auto_decline_zip_override":false,"ebt_type":"food_stamp","id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"terminal_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","account_holder_name":"smith","account_type":"checking","t' .
                'oken_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","' .
                'auth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_' .
                'present":true,"card_present":true,"check_number":"8520748520963","customer_ip":' .
                '"192.168.0.10","cvv_response":"N","entry_mode_id":"C","emv_receipt_data":{"AID"' .
                ':"a0000000042203","APPLAB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified' .
                '","TSI":"e800","TVR":"0800008000"},"first_six":"545454","last_four":"5454","pay' .
                'ment_method":"cc","terminal_serial_number":"1234567890","transaction_settlement' .
                '_status":null,"charge_back_date":"2021-12-01","is_recurring":true,"notification' .
                '_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"' .
                'recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01","status_cod' .
                'e":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED",' .
                '"voucher_number":"1234","void_date":"2021-12-01","batch":"2","terms_agree":true' .
                ',"response_message":null,"return_date":"2021-12-01","trx_source_id":8,"routing_' .
                'number":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_' .
                'user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is_token":tr' .
                'ue,"installment_total":1,"installment_counter":1,"account_vault_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"}],"cc_produ' .
                'ct_transaction":{"processor_version":"1_0_0","title":"My terminal","payment_met' .
                'hod":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"' .
                'standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_' .
                'data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"a' .
                'ch_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":t' .
                'rue,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receip' .
                't_show_contact_name":true,"display_avs":true,"card_type_visa":true,"card_type_m' .
                'c":true,"card_type_disc":true,"card_type_amex":true,"card_type_diners":true,"ca' .
                'rd_type_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt' .
                '_food_stamp":true,"invoice_location":true,"allow_partial_authorization":true,"a' .
                'llow_recurring_partial_authorization":true,"auto_decline_cvv":true,"auto_declin' .
                'e_street":true,"auto_decline_zip":true,"split_payments_allow":true,"vt_show_cus' .
                'tom_fields":true,"receipt_show_custom_fields":true,"vt_override_sales_tax_allow' .
                'ed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_require_street":t' .
                'rue,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_batch":null,"pay' .
                'link_allow":false,"quick_invoice_allow":false,"level3_allow":false,"payfac_enab' .
                'le":false,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","host' .
                'ed_payment_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_b' .
                'ig_commerce":false,"level3_default":{"destination_country_code":"840","duty_amo' .
                'unt":0,"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":' .
                '"AZ12345","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","customer' .
                '_vat_registration":"12345678","merchant_vat_registration":"123456","order_date"' .
                ':"171006","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":' .
                '"vat1234","line_items":[{"alternate_tax_id":"1234","debit_credit":"C","descript' .
                'ion":"cool drink","discount_amount":10,"discount_rate":11,"product_code":"coke1' .
                '2345678","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_' .
                'type_id":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"cc123456","oth' .
                'er_tax_amount":0}]},"cau_subscribe_type_id":0,"location_billing_account_id":"11' .
                'eb88b873980c64a21e5fd2","product_billing_group_id":"nofees","account_number":"1' .
                '2345678","run_avs_on_accountvault_create":false,"accountvault_expire_notificati' .
                'on_email_enable":false,"debit_allow_void":false,"quick_invoice_text_to_pay":fal' .
                'se,"sms_enable":false,"vt_show_currency":true,"receipt_show_currency":false,"al' .
                'low_blind_refund":false,"vt_show_company_name":false,"receipt_show_company_name' .
                '":false,"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,"require_cvv_o' .
                'n_tokenized_cnp":true,"show_secondary_amount":false,"allow_secondary_amount":fa' .
                'lse,"show_google_pay":true,"show_apple_pay":true,"batch_risk_config":{},"curren' .
                'cy_code":840,"enable_ach_validation":false,"enable_ach_retry":false,"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":142204' .
                '0992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_se' .
                'condary_amount_allowed":false,"fortis_id":"8149742","product_billing_group_code' .
                '":"nofees","cau_subscribe_type_code":0},"ach_product_transaction":{"processor_v' .
                'ersion":"1_0_0","title":"My terminal","payment_method":"cc","processor":"zgate"' .
                ',"mcc":"1111","tax_surcharge_config":2,"partner":"standalone","location_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt_clerk_number":tr' .
                'ue,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allow_debit":true,"ach_all' .
                'ow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt_street":true,"vt_zip"' .
                ':true,"vt_order_num":true,"vt_enable":true,"receipt_show_contact_name":true,"di' .
                'splay_avs":true,"card_type_visa":true,"card_type_mc":true,"card_type_disc":true' .
                ',"card_type_amex":true,"card_type_diners":true,"card_type_jcb":true,"card_type_' .
                'ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_stamp":true,"invoice_lo' .
                'cation":true,"allow_partial_authorization":true,"allow_recurring_partial_author' .
                'ization":true,"auto_decline_cvv":true,"auto_decline_street":true,"auto_decline_' .
                'zip":true,"split_payments_allow":true,"vt_show_custom_fields":true,"receipt_sho' .
                'w_custom_fields":true,"vt_override_sales_tax_allowed":true,"vt_enable_sales_tax' .
                '":true,"vt_require_zip":true,"vt_require_street":true,"auto_decline_cavv":true,' .
                '"current_batch":34,"dup_check_per_batch":null,"paylink_allow":false,"quick_invo' .
                'ice_allow":false,"level3_allow":false,"payfac_enable":false,"enable_3ds":false,' .
                '"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,' .
                '"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce":false,"level3_de' .
                'fault":{"destination_country_code":"840","duty_amount":0,"freight_amount":0,"na' .
                'tional_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ12345","shipto_zip_code":"' .
                'MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_registration":"12345678"' .
                ',"merchant_vat_registration":"123456","order_date":"171006","summary_commodity_' .
                'code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","line_items":[{"alt' .
                'ernate_tax_id":"1234","debit_credit":"C","description":"cool drink","discount_a' .
                'mount":10,"discount_rate":11,"product_code":"coke12345678","quantity":5,"tax_am' .
                'ount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id":"a1","unit_code":"gl' .
                'l","unit_cost":10,"commodity_code":"cc123456","other_tax_amount":0}]},"cau_subs' .
                'cribe_type_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","prod' .
                'uct_billing_group_id":"nofees","account_number":"12345678","run_avs_on_accountv' .
                'ault_create":false,"accountvault_expire_notification_email_enable":false,"debit' .
                '_allow_void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_sho' .
                'w_currency":true,"receipt_show_currency":false,"allow_blind_refund":false,"vt_s' .
                'how_company_name":false,"receipt_show_company_name":false,"bank_funded_only":fa' .
                'lse,"require_cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_cnp":true,"show_s' .
                'econdary_amount":false,"allow_secondary_amount":false,"show_google_pay":true,"s' .
                'how_apple_pay":true,"batch_risk_config":{},"currency_code":840,"enable_ach_vali' .
                'dation":false,"enable_ach_retry":false,"id":"11e95f8ec39de8fbdb0a4f1a","active"' .
                ':true,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","product_tra' .
                'nsaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_allowed":false' .
                ',"fortis_id":"8149742","product_billing_group_code":"nofees","cau_subscribe_typ' .
                'e_code":0},"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":t' .
                'rue,"detail":true,"created_ts":1422040992},"sms_blacklist":{"id":"11e95f8ec39de' .
                '8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":1422040992}}}'
            )))
            ->assert();
    }

    public function testResend()
    {
        // Parameters for the API call
        $quickInvoiceId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $email = null;
        $sms = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->resend($quickInvoiceId, $expand, $email, $sms);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(201)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"QuickInvoiceResend","data":{"id":"11e95f8ec39de8fbdb0a4f1a","email_lo' .
                'g_id":"11e95f8ec39de8fbdb0a4f1a","sms_log_id":"11e95f8ec39de8fbdb0a4f1a","succe' .
                'ss":true,"sms_success":true,"email":"email@domain.com"}}'
            )))
            ->assert();
    }

    public function testViewSingleQuickInvoiceRecord()
    {
        // Parameters for the API call
        $quickInvoiceId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleQuickInvoiceRecord($quickInvoiceId, $expand, $fields);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"QuickInvoice","data":{"location_id":"11e95f8ec39de8fbdb0a4f1a","title' .
                '":"My terminal","cc_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","ach_pro' .
                'duct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","due_date":"2021-12-01","item_l' .
                'ist":[{"name":"Bread","amount":2015}],"allow_overpayment":true,"bank_funded_onl' .
                'y_override":true,"email":"email@domain.com","contact_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","contact_api_id":"contact12345","quick_invoice_api_id":"quickinvoice12345"' .
                ',"customer_id":"11e95f8ec39de8fbdb0a4f1a","expire_date":"2021-12-01","allow_par' .
                'tial_pay":true,"attach_files_to_email":true,"send_email":true,"invoice_number":' .
                '"invoice12345","item_header":"Quick invoice header sample","item_footer":"Thank' .
                ' you","amount_due":245.36,"notification_email":"email@domain.com","status_id":1' .
                ',"status_code":1,"note":"some note","notification_days_before_due_date":3,"noti' .
                'fication_days_after_due_date":7,"notification_on_due_date":true,"send_text_to_p' .
                'ay":true,"files":[{"file":{},"resource_id":"11e95f8ec39de8fbdb0a4f1a","resource' .
                '":"Contact","product_file_id":"11e95f8ec39de8fbdb0a4f1a","file_category_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","visibility_group_id":"11e95f8ec39de8fbdb0a4f1a","id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"cre' .
                'ated_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"remaining_balance":245.36,"single_p' .
                'ayment_min_amount":500,"single_payment_max_amount":500000,"cell_phone":"3339998' .
                '822","tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}' .
                '],"quick_invoice_c1":"custom-data-1","quick_invoice_c2":"custom-data-2","quick_' .
                'invoice_c3":"custom-data-3","auto_reopen":true,"id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","active":true,"pay' .
                'ment_status_id":1,"is_active":true,"quick_invoice_setting":{"location_api_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","location_id":"11e95f8ec39de8fbdb0a4f1a","quick_invoi' .
                'ce_template":"<html>Template<html>","default_allow_partial_pay":true,"default_n' .
                'otification_on_due_date":true,"default_notification_days_after_due_date":7,"def' .
                'ault_notification_days_before_due_date":3,"show_custom_fields":false,"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a"},"quick_invoice_views":[{"id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"quick_invoice_id":"Quick Invoice ID","created_ts":1422040992}],"location":{"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'account_number":"5454545454545454","address":{"city":"Novi","state":"MI","posta' .
                'l_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242b' .
                'b2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domain.com"' .
                ',"fax":"3339998822","location_api_id":"location-111111","location_api_key":"AE3' .
                '4BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","locat' .
                'ion_c3":"custom data 3","name":"Sample Company Headquarters","office_phone":"24' .
                '81234567","office_ext_phone":"1021021209","tz":"America/New_York","parent_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":true,"' .
                'created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","ticket_' .
                'hash_key":"A5F443CADF4AE34BBCAADF4"},"created_user":{"account_number":"54545454' .
                '54545454","branding_domain_url":"{branding_domain_url}","cell_phone":"333999882' .
                '2","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","e' .
                'mail":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998822","fi' .
                'rst_name":"John","last_name":"Smith","locale":"en-US","office_phone":"333999882' .
                '2","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","req' .
                'uires_new_password":null,"terms_condition_code":"20220308","tz":"America/New_Yo' .
                'rk","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type":"cs' .
                'v","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a' .
                '4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_has' .
                'h_key":null,"user_type_code":100,"password":null,"zip":"48375","location_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false' .
                ',"address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":' .
                '1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.' .
                '168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login":142204' .
                '0992,"log_api_response_body_ts":1422040992},"modified_user":{"account_number":"' .
                '5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone":"3' .
                '339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998' .
                '822","first_name":"John","last_name":"Smith","locale":"en-US","office_phone":"3' .
                '339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"Americ' .
                'a/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_t' .
                'ype":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39d' .
                'e8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","' .
                'user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","locatio' .
                'n_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitatio' .
                'n":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","country":' .
                '"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_lo' .
                'gin_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_i' .
                'p":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login' .
                '":1422040992,"log_api_response_body_ts":1422040992},"changelogs":[{"id":"11e95f' .
                '8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"Transact' .
                'ionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"' .
                'Bob","last_name":"Fairview"}}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_number":"54545433332","contact_api_id":"137","first_name":"John","' .
                'last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city"' .
                ':"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"company_name' .
                '":"Fortis Payment Systems, LLC","header_message":"This is a sample message for ' .
                'you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999' .
                '8822","office_phone":"3339998822","office_phone_ext":"5","home_phone_country_co' .
                'de":"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","heade' .
                'r_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anythin' .
                'g","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"ema' .
                'il@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"cr' .
                'eated_user_id":"11e95f8ec39de8fbdb0a4f1a"},"log_emails":[{"subject":"Payment Re' .
                'ceipt - 12skiestech","body":"This email is being sent from a server.","source_a' .
                'ddress":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"1' .
                '2skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-' .
                'e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_model_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>"' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"log_sms":{"id":"11e' .
                '95f8ec39de8fbdb0a4f1a","body":" ","reason_model":" ","reason_model_id":" ","pro' .
                'vider_id":" ","status":" ","sender":" ","recipient":" ","created_ts":1422040992' .
                ',"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"transactions":[{"additional_amo' .
                'unts":[{"type":"cashback","amount":10,"account_type":"credit","currency":840}],' .
                '"billing_address":{"city":"Novi","state":"Michigan","postal_code":"48375","phon' .
                'e":"3339998822","country":"USA"},"checkin_date":"2021-12-01","checkout_date":"2' .
                '021-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec39de8fbdb0a4f1a","cus' .
                'tom_data":{},"customer_id":"customerid","description":"some description","ident' .
                'ity_verification":{"dl_state":"MI","dl_number":"1235567","dob_year":"1980"},"ii' .
                'as_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","ima' .
                'ge_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","installment":true,' .
                '"installment_number":1,"installment_count":1,"location_api_id":"location-api-id' .
                '-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"notification' .
                '_email_address":"johnsmith@smiths.com","order_number":"433659378839","po_number' .
                '":"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recurring":fals' .
                'e,"recurring_number":1,"room_num":"303","room_rate":95,"save_account":false,"sa' .
                've_account_title":"John Account","subtotal_amount":599,"surcharge_amount":100,"' .
                'tags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transaction_amount":0,"secon' .
                'dary_amount":0,"transaction_api_id":"transaction-payment-abcd123","transaction_' .
                'c1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c3":"custom-d' .
                'ata-3","bank_funded_only_override":false,"allow_partial_authorization_override"' .
                ':false,"auto_decline_cvv_override":false,"auto_decline_street_override":false,"' .
                'auto_decline_zip_override":false,"ebt_type":"food_stamp","id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"terminal_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","account_holder_name":"smith","account_type":"checking","t' .
                'oken_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","' .
                'auth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_' .
                'present":true,"card_present":true,"check_number":"8520748520963","customer_ip":' .
                '"192.168.0.10","cvv_response":"N","entry_mode_id":"C","emv_receipt_data":{"AID"' .
                ':"a0000000042203","APPLAB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified' .
                '","TSI":"e800","TVR":"0800008000"},"first_six":"545454","last_four":"5454","pay' .
                'ment_method":"cc","terminal_serial_number":"1234567890","transaction_settlement' .
                '_status":null,"charge_back_date":"2021-12-01","is_recurring":true,"notification' .
                '_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"' .
                'recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01","status_cod' .
                'e":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED",' .
                '"voucher_number":"1234","void_date":"2021-12-01","batch":"2","terms_agree":true' .
                ',"response_message":null,"return_date":"2021-12-01","trx_source_id":8,"routing_' .
                'number":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_' .
                'user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is_token":tr' .
                'ue,"installment_total":1,"installment_counter":1,"account_vault_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"}],"cc_produ' .
                'ct_transaction":{"processor_version":"1_0_0","title":"My terminal","payment_met' .
                'hod":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"' .
                'standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_' .
                'data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"a' .
                'ch_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":t' .
                'rue,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receip' .
                't_show_contact_name":true,"display_avs":true,"card_type_visa":true,"card_type_m' .
                'c":true,"card_type_disc":true,"card_type_amex":true,"card_type_diners":true,"ca' .
                'rd_type_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt' .
                '_food_stamp":true,"invoice_location":true,"allow_partial_authorization":true,"a' .
                'llow_recurring_partial_authorization":true,"auto_decline_cvv":true,"auto_declin' .
                'e_street":true,"auto_decline_zip":true,"split_payments_allow":true,"vt_show_cus' .
                'tom_fields":true,"receipt_show_custom_fields":true,"vt_override_sales_tax_allow' .
                'ed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_require_street":t' .
                'rue,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_batch":null,"pay' .
                'link_allow":false,"quick_invoice_allow":false,"level3_allow":false,"payfac_enab' .
                'le":false,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","host' .
                'ed_payment_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_b' .
                'ig_commerce":false,"level3_default":{"destination_country_code":"840","duty_amo' .
                'unt":0,"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":' .
                '"AZ12345","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","customer' .
                '_vat_registration":"12345678","merchant_vat_registration":"123456","order_date"' .
                ':"171006","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":' .
                '"vat1234","line_items":[{"alternate_tax_id":"1234","debit_credit":"C","descript' .
                'ion":"cool drink","discount_amount":10,"discount_rate":11,"product_code":"coke1' .
                '2345678","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_' .
                'type_id":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"cc123456","oth' .
                'er_tax_amount":0}]},"cau_subscribe_type_id":0,"location_billing_account_id":"11' .
                'eb88b873980c64a21e5fd2","product_billing_group_id":"nofees","account_number":"1' .
                '2345678","run_avs_on_accountvault_create":false,"accountvault_expire_notificati' .
                'on_email_enable":false,"debit_allow_void":false,"quick_invoice_text_to_pay":fal' .
                'se,"sms_enable":false,"vt_show_currency":true,"receipt_show_currency":false,"al' .
                'low_blind_refund":false,"vt_show_company_name":false,"receipt_show_company_name' .
                '":false,"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,"require_cvv_o' .
                'n_tokenized_cnp":true,"show_secondary_amount":false,"allow_secondary_amount":fa' .
                'lse,"show_google_pay":true,"show_apple_pay":true,"batch_risk_config":{},"curren' .
                'cy_code":840,"enable_ach_validation":false,"enable_ach_retry":false,"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":142204' .
                '0992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_se' .
                'condary_amount_allowed":false,"fortis_id":"8149742","product_billing_group_code' .
                '":"nofees","cau_subscribe_type_code":0},"ach_product_transaction":{"processor_v' .
                'ersion":"1_0_0","title":"My terminal","payment_method":"cc","processor":"zgate"' .
                ',"mcc":"1111","tax_surcharge_config":2,"partner":"standalone","location_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt_clerk_number":tr' .
                'ue,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allow_debit":true,"ach_all' .
                'ow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt_street":true,"vt_zip"' .
                ':true,"vt_order_num":true,"vt_enable":true,"receipt_show_contact_name":true,"di' .
                'splay_avs":true,"card_type_visa":true,"card_type_mc":true,"card_type_disc":true' .
                ',"card_type_amex":true,"card_type_diners":true,"card_type_jcb":true,"card_type_' .
                'ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_stamp":true,"invoice_lo' .
                'cation":true,"allow_partial_authorization":true,"allow_recurring_partial_author' .
                'ization":true,"auto_decline_cvv":true,"auto_decline_street":true,"auto_decline_' .
                'zip":true,"split_payments_allow":true,"vt_show_custom_fields":true,"receipt_sho' .
                'w_custom_fields":true,"vt_override_sales_tax_allowed":true,"vt_enable_sales_tax' .
                '":true,"vt_require_zip":true,"vt_require_street":true,"auto_decline_cavv":true,' .
                '"current_batch":34,"dup_check_per_batch":null,"paylink_allow":false,"quick_invo' .
                'ice_allow":false,"level3_allow":false,"payfac_enable":false,"enable_3ds":false,' .
                '"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,' .
                '"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce":false,"level3_de' .
                'fault":{"destination_country_code":"840","duty_amount":0,"freight_amount":0,"na' .
                'tional_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ12345","shipto_zip_code":"' .
                'MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_registration":"12345678"' .
                ',"merchant_vat_registration":"123456","order_date":"171006","summary_commodity_' .
                'code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","line_items":[{"alt' .
                'ernate_tax_id":"1234","debit_credit":"C","description":"cool drink","discount_a' .
                'mount":10,"discount_rate":11,"product_code":"coke12345678","quantity":5,"tax_am' .
                'ount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id":"a1","unit_code":"gl' .
                'l","unit_cost":10,"commodity_code":"cc123456","other_tax_amount":0}]},"cau_subs' .
                'cribe_type_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","prod' .
                'uct_billing_group_id":"nofees","account_number":"12345678","run_avs_on_accountv' .
                'ault_create":false,"accountvault_expire_notification_email_enable":false,"debit' .
                '_allow_void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_sho' .
                'w_currency":true,"receipt_show_currency":false,"allow_blind_refund":false,"vt_s' .
                'how_company_name":false,"receipt_show_company_name":false,"bank_funded_only":fa' .
                'lse,"require_cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_cnp":true,"show_s' .
                'econdary_amount":false,"allow_secondary_amount":false,"show_google_pay":true,"s' .
                'how_apple_pay":true,"batch_risk_config":{},"currency_code":840,"enable_ach_vali' .
                'dation":false,"enable_ach_retry":false,"id":"11e95f8ec39de8fbdb0a4f1a","active"' .
                ':true,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","product_tra' .
                'nsaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_allowed":false' .
                ',"fortis_id":"8149742","product_billing_group_code":"nofees","cau_subscribe_typ' .
                'e_code":0},"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":t' .
                'rue,"detail":true,"created_ts":1422040992},"sms_blacklist":{"id":"11e95f8ec39de' .
                '8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":1422040992}}}'
            )))
            ->assert();
    }

    public function testReopenQuickInvoice()
    {
        // Parameters for the API call
        $quickInvoiceId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->reopenQuickInvoice($quickInvoiceId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(201)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"QuickInvoice","data":{"location_id":"11e95f8ec39de8fbdb0a4f1a","title' .
                '":"My terminal","cc_product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","ach_pro' .
                'duct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","due_date":"2021-12-01","item_l' .
                'ist":[{"name":"Bread","amount":2015}],"allow_overpayment":true,"bank_funded_onl' .
                'y_override":true,"email":"email@domain.com","contact_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","contact_api_id":"contact12345","quick_invoice_api_id":"quickinvoice12345"' .
                ',"customer_id":"11e95f8ec39de8fbdb0a4f1a","expire_date":"2021-12-01","allow_par' .
                'tial_pay":true,"attach_files_to_email":true,"send_email":true,"invoice_number":' .
                '"invoice12345","item_header":"Quick invoice header sample","item_footer":"Thank' .
                ' you","amount_due":245.36,"notification_email":"email@domain.com","status_id":1' .
                ',"status_code":1,"note":"some note","notification_days_before_due_date":3,"noti' .
                'fication_days_after_due_date":7,"notification_on_due_date":true,"send_text_to_p' .
                'ay":true,"files":[{"file":{},"resource_id":"11e95f8ec39de8fbdb0a4f1a","resource' .
                '":"Contact","product_file_id":"11e95f8ec39de8fbdb0a4f1a","file_category_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","visibility_group_id":"11e95f8ec39de8fbdb0a4f1a","id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"cre' .
                'ated_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"remaining_balance":245.36,"single_p' .
                'ayment_min_amount":500,"single_payment_max_amount":500000,"cell_phone":"3339998' .
                '822","tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}' .
                '],"quick_invoice_c1":"custom-data-1","quick_invoice_c2":"custom-data-2","quick_' .
                'invoice_c3":"custom-data-3","auto_reopen":true,"id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","active":true,"pay' .
                'ment_status_id":1,"is_active":true,"quick_invoice_setting":{"location_api_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","location_id":"11e95f8ec39de8fbdb0a4f1a","quick_invoi' .
                'ce_template":"<html>Template<html>","default_allow_partial_pay":true,"default_n' .
                'otification_on_due_date":true,"default_notification_days_after_due_date":7,"def' .
                'ault_notification_days_before_due_date":3,"show_custom_fields":false,"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a"},"quick_invoice_views":[{"id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"quick_invoice_id":"Quick Invoice ID","created_ts":1422040992}],"location":{"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'account_number":"5454545454545454","address":{"city":"Novi","state":"MI","posta' .
                'l_code":"48375","country":"US"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242b' .
                'b2","default_cc":"11e608a442a5f1e092242dda","email_reply_to":"email@domain.com"' .
                ',"fax":"3339998822","location_api_id":"location-111111","location_api_key":"AE3' .
                '4BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","locat' .
                'ion_c3":"custom data 3","name":"Sample Company Headquarters","office_phone":"24' .
                '81234567","office_ext_phone":"1021021209","tz":"America/New_York","parent_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","show_contact_notes":true,"show_contact_files":true,"' .
                'created_user_id":"11e95f8ec39de8fbdb0a4f1a","location_type":"merchant","ticket_' .
                'hash_key":"A5F443CADF4AE34BBCAADF4"},"created_user":{"account_number":"54545454' .
                '54545454","branding_domain_url":"{branding_domain_url}","cell_phone":"333999882' .
                '2","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","e' .
                'mail":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998822","fi' .
                'rst_name":"John","last_name":"Smith","locale":"en-US","office_phone":"333999882' .
                '2","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","req' .
                'uires_new_password":null,"terms_condition_code":"20220308","tz":"America/New_Yo' .
                'rk","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type":"cs' .
                'v","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a' .
                '4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_has' .
                'h_key":null,"user_type_code":100,"password":null,"zip":"48375","location_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitation":false' .
                ',"address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"},"i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":' .
                '1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.' .
                '168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login":142204' .
                '0992,"log_api_response_body_ts":1422040992},"modified_user":{"account_number":"' .
                '5454545454545454","branding_domain_url":"{branding_domain_url}","cell_phone":"3' .
                '339998822","company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998' .
                '822","first_name":"John","last_name":"Smith","locale":"en-US","office_phone":"3' .
                '339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","requires_new_password":null,"terms_condition_code":"20220308","tz":"Americ' .
                'a/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_t' .
                'ype":"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39d' .
                'e8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","' .
                'user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","locatio' .
                'n_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_only":false,"is_invitatio' .
                'n":false,"address":{"city":"Novi","state":"MI","postal_code":"48375","country":' .
                '"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_lo' .
                'gin_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_i' .
                'p":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","current_login' .
                '":1422040992,"log_api_response_body_ts":1422040992},"changelogs":[{"id":"11e95f' .
                '8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","model":"Transact' .
                'ionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"1643616000"}],"user' .
                '":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com","first_name":"' .
                'Bob","last_name":"Fairview"}}],"contact":{"location_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_number":"54545433332","contact_api_id":"137","first_name":"John","' .
                'last_name":"Smith","cell_phone":"3339998822","balance":245.36,"address":{"city"' .
                ':"Novi","state":"Michigan","postal_code":"48375","country":"USA"},"company_name' .
                '":"Fortis Payment Systems, LLC","header_message":"This is a sample message for ' .
                'you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"333999' .
                '8822","office_phone":"3339998822","office_phone_ext":"5","home_phone_country_co' .
                'de":"+1","office_phone_country_code":"+1","cell_phone_country_code":"+1","heade' .
                'r_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anythin' .
                'g","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"ema' .
                'il@domain.com","token_import_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true,"cr' .
                'eated_user_id":"11e95f8ec39de8fbdb0a4f1a"},"log_emails":[{"subject":"Payment Re' .
                'ceipt - 12skiestech","body":"This email is being sent from a server.","source_a' .
                'ddress":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"1' .
                '2skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-' .
                'e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_model_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>"' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"log_sms":{"id":"11e' .
                '95f8ec39de8fbdb0a4f1a","body":" ","reason_model":" ","reason_model_id":" ","pro' .
                'vider_id":" ","status":" ","sender":" ","recipient":" ","created_ts":1422040992' .
                ',"created_user_id":"11e95f8ec39de8fbdb0a4f1a"},"transactions":[{"additional_amo' .
                'unts":[{"type":"cashback","amount":10,"account_type":"credit","currency":840}],' .
                '"billing_address":{"city":"Novi","state":"Michigan","postal_code":"48375","phon' .
                'e":"3339998822","country":"USA"},"checkin_date":"2021-12-01","checkout_date":"2' .
                '021-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec39de8fbdb0a4f1a","cus' .
                'tom_data":{},"customer_id":"customerid","description":"some description","ident' .
                'ity_verification":{"dl_state":"MI","dl_number":"1235567","dob_year":"1980"},"ii' .
                'as_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","ima' .
                'ge_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","installment":true,' .
                '"installment_number":1,"installment_count":1,"location_api_id":"location-api-id' .
                '-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"notification' .
                '_email_address":"johnsmith@smiths.com","order_number":"433659378839","po_number' .
                '":"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recurring":fals' .
                'e,"recurring_number":1,"room_num":"303","room_rate":95,"save_account":false,"sa' .
                've_account_title":"John Account","subtotal_amount":599,"surcharge_amount":100,"' .
                'tags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transaction_amount":0,"secon' .
                'dary_amount":0,"transaction_api_id":"transaction-payment-abcd123","transaction_' .
                'c1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c3":"custom-d' .
                'ata-3","bank_funded_only_override":false,"allow_partial_authorization_override"' .
                ':false,"auto_decline_cvv_override":false,"auto_decline_street_override":false,"' .
                'auto_decline_zip_override":false,"ebt_type":"food_stamp","id":"11e95f8ec39de8fb' .
                'db0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"terminal_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","account_holder_name":"smith","account_type":"checking","t' .
                'oken_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","' .
                'auth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_' .
                'present":true,"card_present":true,"check_number":"8520748520963","customer_ip":' .
                '"192.168.0.10","cvv_response":"N","entry_mode_id":"C","emv_receipt_data":{"AID"' .
                ':"a0000000042203","APPLAB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified' .
                '","TSI":"e800","TVR":"0800008000"},"first_six":"545454","last_four":"5454","pay' .
                'ment_method":"cc","terminal_serial_number":"1234567890","transaction_settlement' .
                '_status":null,"charge_back_date":"2021-12-01","is_recurring":true,"notification' .
                '_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"' .
                'recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01","status_cod' .
                'e":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED",' .
                '"voucher_number":"1234","void_date":"2021-12-01","batch":"2","terms_agree":true' .
                ',"response_message":null,"return_date":"2021-12-01","trx_source_id":8,"routing_' .
                'number":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_' .
                'user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is_token":tr' .
                'ue,"installment_total":1,"installment_counter":1,"account_vault_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"}],"cc_produ' .
                'ct_transaction":{"processor_version":"1_0_0","title":"My terminal","payment_met' .
                'hod":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"' .
                'standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_' .
                'data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"a' .
                'ch_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":t' .
                'rue,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receip' .
                't_show_contact_name":true,"display_avs":true,"card_type_visa":true,"card_type_m' .
                'c":true,"card_type_disc":true,"card_type_amex":true,"card_type_diners":true,"ca' .
                'rd_type_jcb":true,"card_type_ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt' .
                '_food_stamp":true,"invoice_location":true,"allow_partial_authorization":true,"a' .
                'llow_recurring_partial_authorization":true,"auto_decline_cvv":true,"auto_declin' .
                'e_street":true,"auto_decline_zip":true,"split_payments_allow":true,"vt_show_cus' .
                'tom_fields":true,"receipt_show_custom_fields":true,"vt_override_sales_tax_allow' .
                'ed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_require_street":t' .
                'rue,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_batch":null,"pay' .
                'link_allow":false,"quick_invoice_allow":false,"level3_allow":false,"payfac_enab' .
                'le":false,"enable_3ds":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","host' .
                'ed_payment_page_allow":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_b' .
                'ig_commerce":false,"level3_default":{"destination_country_code":"840","duty_amo' .
                'unt":0,"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_code":' .
                '"AZ12345","shipto_zip_code":"MI48335","tax_amount":0,"tax_exempt":"0","customer' .
                '_vat_registration":"12345678","merchant_vat_registration":"123456","order_date"' .
                ':"171006","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":' .
                '"vat1234","line_items":[{"alternate_tax_id":"1234","debit_credit":"C","descript' .
                'ion":"cool drink","discount_amount":10,"discount_rate":11,"product_code":"coke1' .
                '2345678","quantity":5,"tax_amount":3,"tax_rate":0,"tax_type_applied":"22","tax_' .
                'type_id":"a1","unit_code":"gll","unit_cost":10,"commodity_code":"cc123456","oth' .
                'er_tax_amount":0}]},"cau_subscribe_type_id":0,"location_billing_account_id":"11' .
                'eb88b873980c64a21e5fd2","product_billing_group_id":"nofees","account_number":"1' .
                '2345678","run_avs_on_accountvault_create":false,"accountvault_expire_notificati' .
                'on_email_enable":false,"debit_allow_void":false,"quick_invoice_text_to_pay":fal' .
                'se,"sms_enable":false,"vt_show_currency":true,"receipt_show_currency":false,"al' .
                'low_blind_refund":false,"vt_show_company_name":false,"receipt_show_company_name' .
                '":false,"bank_funded_only":false,"require_cvv_on_keyed_cnp":true,"require_cvv_o' .
                'n_tokenized_cnp":true,"show_secondary_amount":false,"allow_secondary_amount":fa' .
                'lse,"show_google_pay":true,"show_apple_pay":true,"batch_risk_config":{},"curren' .
                'cy_code":840,"enable_ach_validation":false,"enable_ach_retry":false,"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":142204' .
                '0992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","product_transaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_se' .
                'condary_amount_allowed":false,"fortis_id":"8149742","product_billing_group_code' .
                '":"nofees","cau_subscribe_type_code":0},"ach_product_transaction":{"processor_v' .
                'ersion":"1_0_0","title":"My terminal","payment_method":"cc","processor":"zgate"' .
                ',"mcc":"1111","tax_surcharge_config":2,"partner":"standalone","location_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt_clerk_number":tr' .
                'ue,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allow_debit":true,"ach_all' .
                'ow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt_street":true,"vt_zip"' .
                ':true,"vt_order_num":true,"vt_enable":true,"receipt_show_contact_name":true,"di' .
                'splay_avs":true,"card_type_visa":true,"card_type_mc":true,"card_type_disc":true' .
                ',"card_type_amex":true,"card_type_diners":true,"card_type_jcb":true,"card_type_' .
                'ebt":true,"allow_ebt_cash_benefit":true,"allow_ebt_food_stamp":true,"invoice_lo' .
                'cation":true,"allow_partial_authorization":true,"allow_recurring_partial_author' .
                'ization":true,"auto_decline_cvv":true,"auto_decline_street":true,"auto_decline_' .
                'zip":true,"split_payments_allow":true,"vt_show_custom_fields":true,"receipt_sho' .
                'w_custom_fields":true,"vt_override_sales_tax_allowed":true,"vt_enable_sales_tax' .
                '":true,"vt_require_zip":true,"vt_require_street":true,"auto_decline_cavv":true,' .
                '"current_batch":34,"dup_check_per_batch":null,"paylink_allow":false,"quick_invo' .
                'ice_allow":false,"level3_allow":false,"payfac_enable":false,"enable_3ds":false,' .
                '"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,' .
                '"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","allow_big_commerce":false,"level3_de' .
                'fault":{"destination_country_code":"840","duty_amount":0,"freight_amount":0,"na' .
                'tional_tax":2,"sales_tax":200,"shipfrom_zip_code":"AZ12345","shipto_zip_code":"' .
                'MI48335","tax_amount":0,"tax_exempt":"0","customer_vat_registration":"12345678"' .
                ',"merchant_vat_registration":"123456","order_date":"171006","summary_commodity_' .
                'code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","line_items":[{"alt' .
                'ernate_tax_id":"1234","debit_credit":"C","description":"cool drink","discount_a' .
                'mount":10,"discount_rate":11,"product_code":"coke12345678","quantity":5,"tax_am' .
                'ount":3,"tax_rate":0,"tax_type_applied":"22","tax_type_id":"a1","unit_code":"gl' .
                'l","unit_cost":10,"commodity_code":"cc123456","other_tax_amount":0}]},"cau_subs' .
                'cribe_type_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","prod' .
                'uct_billing_group_id":"nofees","account_number":"12345678","run_avs_on_accountv' .
                'ault_create":false,"accountvault_expire_notification_email_enable":false,"debit' .
                '_allow_void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_sho' .
                'w_currency":true,"receipt_show_currency":false,"allow_blind_refund":false,"vt_s' .
                'how_company_name":false,"receipt_show_company_name":false,"bank_funded_only":fa' .
                'lse,"require_cvv_on_keyed_cnp":true,"require_cvv_on_tokenized_cnp":true,"show_s' .
                'econdary_amount":false,"allow_secondary_amount":false,"show_google_pay":true,"s' .
                'how_apple_pay":true,"batch_risk_config":{},"currency_code":840,"enable_ach_vali' .
                'dation":false,"enable_ach_retry":false,"id":"11e95f8ec39de8fbdb0a4f1a","active"' .
                ':true,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","product_tra' .
                'nsaction_api_id":"11e95f8ec39de8fbdb0a4f1a","is_secondary_amount_allowed":false' .
                ',"fortis_id":"8149742","product_billing_group_code":"nofees","cau_subscribe_typ' .
                'e_code":0},"email_blacklist":{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":t' .
                'rue,"detail":true,"created_ts":1422040992},"sms_blacklist":{"id":"11e95f8ec39de' .
                '8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":1422040992}}}'
            )))
            ->assert();
    }
}
