<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\TransactionACHRetriesController;
use FortisAPILib\Exceptions;

class TransactionACHRetriesControllerTest extends BaseTestController
{
    /**
     * @var TransactionACHRetriesController TransactionACHRetriesController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getTransactionACHRetriesController();
    }

    public function testViewSingleTransactionACHRetryRecord()
    {
        // Parameters for the API call
        $transactionAchRetryId =
            '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleTransactionACHRetryRecord(
                $transactionAchRetryId,
                $expand,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"TransactionAchRetry","data":{"rejected_transaction_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","retry_transaction_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","return_fee_transaction_id":"11e95f8ec39de8fbdb0a4f1a","created' .
                '_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","rejected_transact' .
                'ion":{"additional_amounts":[{"type":"cashback","amount":10,"account_type":"cred' .
                'it","currency":840}],"billing_address":{"city":"Novi","state":"Michigan","posta' .
                'l_code":"48375","phone":"3339998822","country":"USA"},"checkin_date":"2021-12-0' .
                '1","checkout_date":"2021-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","custom_data":{},"customer_id":"customerid","description":"som' .
                'e description","identity_verification":{"dl_state":"MI","dl_number":"1235567","' .
                'dob_year":"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc' .
                '2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=' .
                '","installment":true,"installment_number":1,"installment_count":1,"location_api' .
                '_id":"location-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","prod' .
                'uct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show' .
                '":false,"notification_email_address":"johnsmith@smiths.com","order_number":"433' .
                '659378839","po_number":"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","recurring":false,"recurring_number":1,"room_num":"303","room_rate":95,"sa' .
                've_account":false,"save_account_title":"John Account","subtotal_amount":599,"su' .
                'rcharge_amount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transac' .
                'tion_amount":0,"secondary_amount":0,"transaction_api_id":"transaction-payment-a' .
                'bcd123","transaction_c1":"custom-data-1","transaction_c2":"custom-data-2","tran' .
                'saction_c3":"custom-data-3","bank_funded_only_override":false,"allow_partial_au' .
                'thorization_override":false,"auto_decline_cvv_override":false,"auto_decline_str' .
                'eet_override":false,"auto_decline_zip_override":false,"ebt_type":"food_stamp","' .
                'id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992' .
                ',"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"smith","accoun' .
                't_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P","' .
                'ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enhan' .
                'ced":"N","cardholder_present":true,"card_present":true,"check_number":"85207485' .
                '20963","customer_ip":"192.168.0.10","cvv_response":"N","entry_mode_id":"C","emv' .
                '_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN":"US Maestro' .
                '","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"first_six":"545454","l' .
                'ast_four":"5454","payment_method":"cc","terminal_serial_number":"1234567890","t' .
                'ransaction_settlement_status":null,"charge_back_date":"2021-12-01","is_recurrin' .
                'g":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","r' .
                'eason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"20' .
                '21-12-01","status_code":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'verbiage":"APPROVED","voucher_number":"1234","void_date":"2021-12-01","batch":"' .
                '2","terms_agree":true,"response_message":null,"return_date":"2021-12-01","trx_s' .
                'ource_id":8,"routing_number":"051904524","trx_source_code":8,"paylink_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","is_accountvault":true,"created_user_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021' .
                '-12-01","is_token":true,"installment_total":1,"installment_counter":1,"account_' .
                'vault_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fb' .
                'db0a4f1a"},"retry_transaction":{"additional_amounts":[{"type":"cashback","amoun' .
                't":10,"account_type":"credit","currency":840}],"billing_address":{"city":"Novi"' .
                ',"state":"Michigan","postal_code":"48375","phone":"3339998822","country":"USA"}' .
                ',"checkin_date":"2021-12-01","checkout_date":"2021-12-01","clerk_number":"AE123' .
                '4","contact_id":"11e95f8ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"cust' .
                'omerid","description":"some description","identity_verification":{"dl_state":"M' .
                'I","dl_number":"1235567","dob_year":"1980"},"iias_ind":1,"image_front":"U29tZVN' .
                '0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdX' .
                'NseU5vdEJhc2U2NEVuY29kZWQ=","installment":true,"installment_number":1,"installm' .
                'ent_count":1,"location_api_id":"location-api-id-florida-2","location_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advan' .
                'ce_deposit":false,"no_show":false,"notification_email_address":"johnsmith@smith' .
                's.com","order_number":"433659378839","po_number":"555555553123","quick_invoice_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","recurring":false,"recurring_number":1,"room_num' .
                '":"303","room_rate":95,"save_account":false,"save_account_title":"John Account"' .
                ',"subtotal_amount":599,"surcharge_amount":100,"tags":["Walk-in Customer"],"tax"' .
                ':0,"tip_amount":0,"transaction_amount":0,"secondary_amount":0,"transaction_api_' .
                'id":"transaction-payment-abcd123","transaction_c1":"custom-data-1","transaction' .
                '_c2":"custom-data-2","transaction_c3":"custom-data-3","bank_funded_only_overrid' .
                'e":false,"allow_partial_authorization_override":false,"auto_decline_cvv_overrid' .
                'e":false,"auto_decline_street_override":false,"auto_decline_zip_override":false' .
                ',"ebt_type":"food_stamp","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204099' .
                '2,"modified_ts":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_ho' .
                'lder_name":"smith","account_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","ach_identifier":"P","ach_sec_code":"C21","auth_amount":1,"auth_code":"BR34' .
                '9K","avs":"BAD","avs_enhanced":"N","cardholder_present":true,"card_present":tru' .
                'e,"check_number":"8520748520963","customer_ip":"192.168.0.10","cvv_response":"N' .
                '","entry_mode_id":"C","emv_receipt_data":{"AID":"a0000000042203","APPLAB":"US M' .
                'aestro","APPN":"US Maestro","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000' .
                '"},"first_six":"545454","last_four":"5454","payment_method":"cc","terminal_seri' .
                'al_number":"1234567890","transaction_settlement_status":null,"charge_back_date"' .
                ':"2021-12-01","is_recurring":true,"notification_email_sent":true,"par":"Q1J4Z28' .
                'RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"recurring_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","settle_date":"2021-12-01","status_code":101,"transaction_batch_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED","voucher_number":"1234","void_da' .
                'te":"2021-12-01","batch":"2","terms_agree":true,"response_message":null,"return' .
                '_date":"2021-12-01","trx_source_id":8,"routing_number":"051904524","trx_source_' .
                'code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a","is_accountvault":true,"created' .
                '_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","effective_date":"2021-12-01","is_token":true,"installment_total":1,"instal' .
                'lment_counter":1,"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_' .
                'page_id":"11e95f8ec39de8fbdb0a4f1a"},"return_fee_transaction":{"additional_amou' .
                'nts":[{"type":"cashback","amount":10,"account_type":"credit","currency":840}],"' .
                'billing_address":{"city":"Novi","state":"Michigan","postal_code":"48375","phone' .
                '":"3339998822","country":"USA"},"checkin_date":"2021-12-01","checkout_date":"20' .
                '21-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec39de8fbdb0a4f1a","cust' .
                'om_data":{},"customer_id":"customerid","description":"some description","identi' .
                'ty_verification":{"dl_state":"MI","dl_number":"1235567","dob_year":"1980"},"iia' .
                's_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","imag' .
                'e_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","installment":true,"' .
                'installment_number":1,"installment_count":1,"location_api_id":"location-api-id-' .
                'florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"notification_' .
                'email_address":"johnsmith@smiths.com","order_number":"433659378839","po_number"' .
                ':"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recurring":false' .
                ',"recurring_number":1,"room_num":"303","room_rate":95,"save_account":false,"sav' .
                'e_account_title":"John Account","subtotal_amount":599,"surcharge_amount":100,"t' .
                'ags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transaction_amount":0,"second' .
                'ary_amount":0,"transaction_api_id":"transaction-payment-abcd123","transaction_c' .
                '1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c3":"custom-da' .
                'ta-3","bank_funded_only_override":false,"allow_partial_authorization_override":' .
                'false,"auto_decline_cvv_override":false,"auto_decline_street_override":false,"a' .
                'uto_decline_zip_override":false,"ebt_type":"food_stamp","id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"terminal_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","account_holder_name":"smith","account_type":"checking","to' .
                'ken_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","a' .
                'uth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_p' .
                'resent":true,"card_present":true,"check_number":"8520748520963","customer_ip":"' .
                '192.168.0.10","cvv_response":"N","entry_mode_id":"C","emv_receipt_data":{"AID":' .
                '"a0000000042203","APPLAB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified"' .
                ',"TSI":"e800","TVR":"0800008000"},"first_six":"545454","last_four":"5454","paym' .
                'ent_method":"cc","terminal_serial_number":"1234567890","transaction_settlement_' .
                'status":null,"charge_back_date":"2021-12-01","is_recurring":true,"notification_' .
                'email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"r' .
                'ecurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01","status_code' .
                '":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED","' .
                'voucher_number":"1234","void_date":"2021-12-01","batch":"2","terms_agree":true,' .
                '"response_message":null,"return_date":"2021-12-01","trx_source_id":8,"routing_n' .
                'umber":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_u' .
                'ser_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","is_token":tru' .
                'e,"installment_total":1,"installment_counter":1,"account_vault_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"},"created_us' .
                'er":{"account_number":"5454545454545454","branding_domain_url":"{branding_domai' .
                'n_url}","cell_phone":"3339998822","company_name":"Fortis Payment Systems, LLC",' .
                '"contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":tru' .
                'e,"home_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"e' .
                'n-US","office_phone":"3339998822","office_ext_phone":"5","primary_location_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_condition_code":' .
                '"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard","page_s' .
                'ize":2,"report_export_type":"csv","process_method":"virtual_terminal","default_' .
                'terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"' .
                '234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"password":null' .
                ',"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_code":1,"api_on' .
                'ly":false,"is_invitation":false,"address":{"city":"Novi","state":"MI","postal_c' .
                'ode":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"log' .
                'in_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_ts"' .
                ':1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":14' .
                '22040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:' .
                '26-0700","current_login":1422040992,"log_api_response_body_ts":1422040992},"cha' .
                'ngelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CR' .
                'EATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_valu' .
                'e":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@dom' .
                'ain.com","first_name":"Bob","last_name":"Fairview"}}]}}'
            )))
            ->assert();
    }

    public function testListAllTransactionACHRetriesRelated()
    {
        // Parameters for the API call
        $page = null;
        $order = null;
        $filterBy = null;
        $expand = null;
        $format = null;
        $typeahead = null;
        $fields = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllTransactionACHRetriesRelated(
                $page,
                $order,
                $filterBy,
                $expand,
                $format,
                $typeahead,
                $fields
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"TransactionAchRetrysCollection","list":[{"rejected_transaction_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","retry_transaction_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","return_fee_transaction_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","rejec' .
                'ted_transaction":{"additional_amounts":[{"type":"cashback","amount":10,"account' .
                '_type":"credit","currency":840}],"billing_address":{"city":"Novi","state":"Mich' .
                'igan","postal_code":"48375","phone":"3339998822","country":"USA"},"checkin_date' .
                '":"2021-12-01","checkout_date":"2021-12-01","clerk_number":"AE1234","contact_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"customerid","descr' .
                'iption":"some description","identity_verification":{"dl_state":"MI","dl_number"' .
                ':"1235567","dob_year":"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvd' .
                'XNseU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2' .
                'NEVuY29kZWQ=","installment":true,"installment_number":1,"installment_count":1,"' .
                'location_api_id":"location-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":fa' .
                'lse,"no_show":false,"notification_email_address":"johnsmith@smiths.com","order_' .
                'number":"433659378839","po_number":"555555553123","quick_invoice_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","recurring":false,"recurring_number":1,"room_num":"303","room_' .
                'rate":95,"save_account":false,"save_account_title":"John Account","subtotal_amo' .
                'unt":599,"surcharge_amount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amount' .
                '":0,"transaction_amount":0,"secondary_amount":0,"transaction_api_id":"transacti' .
                'on-payment-abcd123","transaction_c1":"custom-data-1","transaction_c2":"custom-d' .
                'ata-2","transaction_c3":"custom-data-3","bank_funded_only_override":false,"allo' .
                'w_partial_authorization_override":false,"auto_decline_cvv_override":false,"auto' .
                '_decline_street_override":false,"auto_decline_zip_override":false,"ebt_type":"f' .
                'ood_stamp","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts' .
                '":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"sm' .
                'ith","account_type":"checking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_ident' .
                'ifier":"P","ach_sec_code":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BAD' .
                '","avs_enhanced":"N","cardholder_present":true,"card_present":true,"check_numbe' .
                'r":"8520748520963","customer_ip":"192.168.0.10","cvv_response":"N","entry_mode_' .
                'id":"C","emv_receipt_data":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN"' .
                ':"US Maestro","CVM":"Pin Verified","TSI":"e800","TVR":"0800008000"},"first_six"' .
                ':"545454","last_four":"5454","payment_method":"cc","terminal_serial_number":"12' .
                '34567890","transaction_settlement_status":null,"charge_back_date":"2021-12-01",' .
                '"is_recurring":true,"notification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XY' .
                'G90R5D3E","reason_code_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","sett' .
                'le_date":"2021-12-01","status_code":101,"transaction_batch_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","verbiage":"APPROVED","voucher_number":"1234","void_date":"2021-12-0' .
                '1","batch":"2","terms_agree":true,"response_message":null,"return_date":"2021-1' .
                '2-01","trx_source_id":8,"routing_number":"051904524","trx_source_code":8,"payli' .
                'nk_id":"11e95f8ec39de8fbdb0a4f1a","is_accountvault":true,"created_user_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","effective' .
                '_date":"2021-12-01","is_token":true,"installment_total":1,"installment_counter"' .
                ':1,"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a"},"retry_transaction":{"additional_amounts":[{"type":"cash' .
                'back","amount":10,"account_type":"credit","currency":840}],"billing_address":{"' .
                'city":"Novi","state":"Michigan","postal_code":"48375","phone":"3339998822","cou' .
                'ntry":"USA"},"checkin_date":"2021-12-01","checkout_date":"2021-12-01","clerk_nu' .
                'mber":"AE1234","contact_id":"11e95f8ec39de8fbdb0a4f1a","custom_data":{},"custom' .
                'er_id":"customerid","description":"some description","identity_verification":{"' .
                'dl_state":"MI","dl_number":"1235567","dob_year":"1980"},"iias_ind":1,"image_fro' .
                'nt":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cm' .
                'luZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","installment":true,"installment_number"' .
                ':1,"installment_count":1,"location_api_id":"location-api-id-florida-2","locatio' .
                'n_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","advance_deposit":false,"no_show":false,"notification_email_address":"joh' .
                'nsmith@smiths.com","order_number":"433659378839","po_number":"555555553123","qu' .
                'ick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recurring":false,"recurring_number"' .
                ':1,"room_num":"303","room_rate":95,"save_account":false,"save_account_title":"J' .
                'ohn Account","subtotal_amount":599,"surcharge_amount":100,"tags":["Walk-in Cust' .
                'omer"],"tax":0,"tip_amount":0,"transaction_amount":0,"secondary_amount":0,"tran' .
                'saction_api_id":"transaction-payment-abcd123","transaction_c1":"custom-data-1",' .
                '"transaction_c2":"custom-data-2","transaction_c3":"custom-data-3","bank_funded_' .
                'only_override":false,"allow_partial_authorization_override":false,"auto_decline' .
                '_cvv_override":false,"auto_decline_street_override":false,"auto_decline_zip_ove' .
                'rride":false,"ebt_type":"food_stamp","id":"11e95f8ec39de8fbdb0a4f1a","created_t' .
                's":1422040992,"modified_ts":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"account_holder_name":"smith","account_type":"checking","token_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","auth_amount":1,"auth' .
                '_code":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_present":true,"card_' .
                'present":true,"check_number":"8520748520963","customer_ip":"192.168.0.10","cvv_' .
                'response":"N","entry_mode_id":"C","emv_receipt_data":{"AID":"a0000000042203","A' .
                'PPLAB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified","TSI":"e800","TVR"' .
                ':"0800008000"},"first_six":"545454","last_four":"5454","payment_method":"cc","t' .
                'erminal_serial_number":"1234567890","transaction_settlement_status":null,"charg' .
                'e_back_date":"2021-12-01","is_recurring":true,"notification_email_sent":true,"p' .
                'ar":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"recurring_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01","status_code":101,"transaction_' .
                'batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED","voucher_number":"12' .
                '34","void_date":"2021-12-01","batch":"2","terms_agree":true,"response_message":' .
                'null,"return_date":"2021-12-01","trx_source_id":8,"routing_number":"051904524",' .
                '"trx_source_code":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a","is_accountvault":t' .
                'rue,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","effective_date":"2021-12-01","is_token":true,"installment_tota' .
                'l":1,"installment_counter":1,"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","hos' .
                'ted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"},"return_fee_transaction":{"add' .
                'itional_amounts":[{"type":"cashback","amount":10,"account_type":"credit","curre' .
                'ncy":840}],"billing_address":{"city":"Novi","state":"Michigan","postal_code":"4' .
                '8375","phone":"3339998822","country":"USA"},"checkin_date":"2021-12-01","checko' .
                'ut_date":"2021-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","custom_data":{},"customer_id":"customerid","description":"some descript' .
                'ion","identity_verification":{"dl_state":"MI","dl_number":"1235567","dob_year":' .
                '"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29' .
                'kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","install' .
                'ment":true,"installment_number":1,"installment_count":1,"location_api_id":"loca' .
                'tion-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_transa' .
                'ction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"n' .
                'otification_email_address":"johnsmith@smiths.com","order_number":"433659378839"' .
                ',"po_number":"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recu' .
                'rring":false,"recurring_number":1,"room_num":"303","room_rate":95,"save_account' .
                '":false,"save_account_title":"John Account","subtotal_amount":599,"surcharge_am' .
                'ount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transaction_amoun' .
                't":0,"secondary_amount":0,"transaction_api_id":"transaction-payment-abcd123","t' .
                'ransaction_c1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c3' .
                '":"custom-data-3","bank_funded_only_override":false,"allow_partial_authorizatio' .
                'n_override":false,"auto_decline_cvv_override":false,"auto_decline_street_overri' .
                'de":false,"auto_decline_zip_override":false,"ebt_type":"food_stamp","id":"11e95' .
                'f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"terminal' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","account_holder_name":"smith","account_type":"c' .
                'hecking","token_id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_co' .
                'de":"C21","auth_amount":1,"auth_code":"BR349K","avs":"BAD","avs_enhanced":"N","' .
                'cardholder_present":true,"card_present":true,"check_number":"8520748520963","cu' .
                'stomer_ip":"192.168.0.10","cvv_response":"N","entry_mode_id":"C","emv_receipt_d' .
                'ata":{"AID":"a0000000042203","APPLAB":"US Maestro","APPN":"US Maestro","CVM":"P' .
                'in Verified","TSI":"e800","TVR":"0800008000"},"first_six":"545454","last_four":' .
                '"5454","payment_method":"cc","terminal_serial_number":"1234567890","transaction' .
                '_settlement_status":null,"charge_back_date":"2021-12-01","is_recurring":true,"n' .
                'otification_email_sent":true,"par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code' .
                '_id":1000,"recurring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01",' .
                '"status_code":101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":' .
                '"APPROVED","voucher_number":"1234","void_date":"2021-12-01","batch":"2","terms_' .
                'agree":true,"response_message":null,"return_date":"2021-12-01","trx_source_id":' .
                '8,"routing_number":"051904524","trx_source_code":8,"paylink_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","is_accountvault":true,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"modified_user_id":"11e95f8ec39de8fbdb0a4f1a","effective_date":"2021-12-01","i' .
                's_token":true,"installment_total":1,"installment_counter":1,"account_vault_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_id":"11e95f8ec39de8fbdb0a4f1a"}' .
                ',"created_user":{"account_number":"5454545454545454","branding_domain_url":"{br' .
                'anding_domain_url}","cell_phone":"3339998822","company_name":"Fortis Payment Sy' .
                'stems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01' .
                '","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_' .
                'receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith"' .
                ',"locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_l' .
                'ocation_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"terms_cond' .
                'ition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashbo' .
                'ard","page_size":2,"report_export_type":"csv","process_method":"virtual_termina' .
                'l","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","use' .
                'r_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pa' .
                'ssword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_cod' .
                'e":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi","state":"M' .
                'I","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a4f1a","statu' .
                's":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"' .
                'modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_acc' .
                'epted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-' .
                '03-11T10:38:26-0700","current_login":1422040992,"log_api_response_body_ts":1422' .
                '040992},"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,' .
                '"action":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9' .
                'aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8e' .
                'c39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_t' .
                's","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username' .
                '":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}]}],"links":{"t' .
                'ype":"Links","first":"/v1/endpoint?page[size]=10&page[number]=1","previous":"/v' .
                '1/endpoint?page[size]=10&page[number]=5","next":"/v1/endpoint?page[size]=10&pag' .
                'e[number]=7","last":"/v1/endpoint?page[size]=10&page[number]=42"},"pagination":' .
                '{"type":"Pagination","total_count":423,"page_count":42,"page_number":6,"page_si' .
                'ze":10},"sort":{"type":"Sorting","fields":[{"field":"last_name","order":"asc"}]' .
                '}}'
            )))
            ->assert();
    }
}
