<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data27;

/**
 * Builder for model Data27
 *
 * @see Data27
 */
class Data27Builder
{
    /**
     * @var Data27
     */
    private $instance;

    private function __construct(Data27 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Data 27 Builder object.
     */
    public static function init(): self
    {
        return new self(new Data27());
    }

    /**
     * Sets issuer bank name field.
     *
     * @param string|null $value
     */
    public function issuerBankName(?string $value): self
    {
        $this->instance->setIssuerBankName($value);
        return $this;
    }

    /**
     * Sets country code field.
     *
     * @param string|null $value
     */
    public function countryCode(?string $value): self
    {
        $this->instance->setCountryCode($value);
        return $this;
    }

    /**
     * Sets detail card product field.
     *
     * @param string|null $value
     */
    public function detailCardProduct(?string $value): self
    {
        $this->instance->setDetailCardProduct($value);
        return $this;
    }

    /**
     * Sets detail card indicator field.
     *
     * @param string|null $value
     */
    public function detailCardIndicator(?string $value): self
    {
        $this->instance->setDetailCardIndicator($value);
        return $this;
    }

    /**
     * Sets fsa indicator field.
     *
     * @param string|null $value
     */
    public function fsaIndicator(?string $value): self
    {
        $this->instance->setFsaIndicator($value);
        return $this;
    }

    /**
     * Sets prepaid indicator field.
     *
     * @param string|null $value
     */
    public function prepaidIndicator(?string $value): self
    {
        $this->instance->setPrepaidIndicator($value);
        return $this;
    }

    /**
     * Sets product id field.
     *
     * @param string|null $value
     */
    public function productId(?string $value): self
    {
        $this->instance->setProductId($value);
        return $this;
    }

    /**
     * Sets regulator indicator field.
     *
     * @param string|null $value
     */
    public function regulatorIndicator(?string $value): self
    {
        $this->instance->setRegulatorIndicator($value);
        return $this;
    }

    /**
     * Sets visa product sub type field.
     *
     * @param string|null $value
     */
    public function visaProductSubType(?string $value): self
    {
        $this->instance->setVisaProductSubType($value);
        return $this;
    }

    /**
     * Unsets visa product sub type field.
     */
    public function unsetVisaProductSubType(): self
    {
        $this->instance->unsetVisaProductSubType();
        return $this;
    }

    /**
     * Sets visa large ticket indicator field.
     *
     * @param string|null $value
     */
    public function visaLargeTicketIndicator(?string $value): self
    {
        $this->instance->setVisaLargeTicketIndicator($value);
        return $this;
    }

    /**
     * Unsets visa large ticket indicator field.
     */
    public function unsetVisaLargeTicketIndicator(): self
    {
        $this->instance->unsetVisaLargeTicketIndicator();
        return $this;
    }

    /**
     * Sets account fund source field.
     *
     * @param string|null $value
     */
    public function accountFundSource(?string $value): self
    {
        $this->instance->setAccountFundSource($value);
        return $this;
    }

    /**
     * Sets card class field.
     *
     * @param string|null $value
     */
    public function cardClass(?string $value): self
    {
        $this->instance->setCardClass($value);
        return $this;
    }

    /**
     * Unsets card class field.
     */
    public function unsetCardClass(): self
    {
        $this->instance->unsetCardClass();
        return $this;
    }

    /**
     * Sets token ind field.
     *
     * @param string|null $value
     */
    public function tokenInd(?string $value): self
    {
        $this->instance->setTokenInd($value);
        return $this;
    }

    /**
     * Unsets token ind field.
     */
    public function unsetTokenInd(): self
    {
        $this->instance->unsetTokenInd();
        return $this;
    }

    /**
     * Sets issuing network field.
     *
     * @param string|null $value
     */
    public function issuingNetwork(?string $value): self
    {
        $this->instance->setIssuingNetwork($value);
        return $this;
    }

    /**
     * Unsets issuing network field.
     */
    public function unsetIssuingNetwork(): self
    {
        $this->instance->unsetIssuingNetwork();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Data 27 object.
     */
    public function build(): Data27
    {
        return CoreHelper::clone($this->instance);
    }
}
